/*
 * The forms of ide, as classes with their controls.
 *
 * GENERATED by tools/typings -- regenerate with tests/typings.sh.
 */

interface AboutForm {
    PnlContent: Panel;
    ImgAbout: Image;
    LblName: Label;
    LblVersion: Label;
    LblSummary: Label;
    LblCopyright: Label;
    LblRuntime: Label;
    PnlButtons: Panel;
    BtnClose: Button;
}

interface AppForm {
    LblAppName: Label;
    TxtAppName: TextBox;
    LblAppComment: Label;
    TxtAppComment: TextBox;
    LblAppIcon: Label;
    TxtAppIcon: TextBox;
    BtnAppIcon: Button;
    LblAppWhere: Label;
    LblAppHint: Label;
    BtnAppUninstall: Button;
    BtnAppCancel: Button;
    BtnAppInstall: Button;
}

interface AskForm {
    LblPrompt: Label;
    TxtValue: TextBox;
    ChkOption: CheckButton;
    BtnCancel: Button;
    BtnOk: Button;
}

interface ClassForm {
    LblTxtName: Label;
    TxtName: TextBox;
    LblColBack: Label;
    ColBackGroup: Panel;
    ColBack: ColorButton;
    BtnColBackNone: Button;
    LblColFore: Label;
    ColForeGroup: Panel;
    ColFore: ColorButton;
    BtnColForeNone: Button;
    LblTxtFont: Label;
    TxtFont: TextBox;
    LblSpnScale: Label;
    SpnScale: SpinBox;
    LblSpnOpacity: Label;
    SpnOpacity: SpinBox;
    LblTxtBorder: Label;
    TxtBorder: TextBox;
    LblTxtRadius: Label;
    TxtRadius: TextBox;
    LblTxtPadding: Label;
    TxtPadding: TextBox;
    LblTxtShadow: Label;
    TxtShadow: TextBox;
    Preview: Panel;
    Sample: Label;
    LblSays: Label;
    BtnCancel: Button;
    BtnSave: Button;
}

interface ColumnForm {
    LblCols: Label;
    ColList: TableView;
    BtnColAdd: Button;
    BtnColDel: Button;
    BtnColUp: Button;
    BtnColDown: Button;
    LblColText: Label;
    TxtColText: TextBox;
    LblColWidth: Label;
    SpnColWidth: SpinBox;
    LblColAlign: Label;
    CmbColAlign: ComboBox;
    LblColHint: Label;
    BtnColCancel: Button;
    BtnColOk: Button;
}

interface ConfirmForm {
    LblMessage: Label;
    BtnOther: Button;
    BtnNo: Button;
    BtnYes: Button;
}

interface GitForm {
    Top: Split;
    LeftBox: Panel;
    Which: Switcher;
    Unstaged: TableView;
    Staged: TableView;
    RightBox: Panel;
    How: Switcher;
    Pair: Split;
    Before: SourceEditor;
    After: SourceEditor;
    Unified: SourceEditor;
    LblMessage: Label;
    Message: TextEditor;
    Buttons: Panel;
    BtnStage: Button;
    BtnUnstage: Button;
    BtnDiscard: Button;
    LblGitStatus: Label;
    BtnClose: Button;
    BtnCommit: Button;
}

interface HelpForm {
    Halves: Split;
    Pages: TreeView;
    Right: Panel;
    Bar: Panel;
    BtnBack: Button;
    LblWhere: Label;
    TxtFind: TextBox;
    Doc: any;
}

interface IconForm {
    TxtFind: TextBox;
    Board: Flow;
    LblCount: Label;
    BtnNone: Button;
    BtnCancel: Button;
}

interface ImageForm {
    Bar: Panel;
    BtnFit: Button;
    BtnOne: Button;
    BtnOut: Button;
    BtnIn: Button;
    LblAbout: Label;
    BtnClose: Button;
    View: Scroller;
    Shown: Picture;
}

interface LaunchForm {
    LblLcList: Label;
    LstLcNames: ListBox;
    BtnLcAdd: Button;
    BtnLcRemove: Button;
    LblLcName: Label;
    TxtLcName: TextBox;
    LblLcArgs: Label;
    TxtLcArgs: TextEditor;
    LblLcDir: Label;
    TxtLcDir: TextBox;
    LblLcEnv: Label;
    TxtLcEnv: TextEditor;
    ChkLcStrict: CheckButton;
    ChkLcThrow: CheckButton;
    LblLcDefaults: Label;
    BtnLcCancel: Button;
    BtnLcOk: Button;
}

interface LogForm {
    Outer: Split;
    Commits: TableView;
    Below: Split;
    Touched: TableView;
    How: Switcher;
    Pair: Split;
    Before: SourceEditor;
    After: SourceEditor;
    Unified: SourceEditor;
    Foot: Panel;
    LblWhat: Label;
    BtnClose: Button;
}

interface MainForm {
    Pages: Switcher;
    WelcomeBox: Panel;
    WelcomeCol: Panel;
    ImgWelcome: Image;
    LblWelcome: Label;
    LblWelcomeHint: Label;
    BtnWelcomeOpen: Button;
    BtnWelcomeNew: Button;
    LblWelcomeRecent: Label;
    WelcomeRecent: ListBox;
    WorkBox: Panel;
    ToolBar: Panel;
    BtnOpen: Button;
    BtnReload: Button;
    BtnSave: Button;
    RunGroup: Panel;
    BtnRun: Button;
    BtnStop: Button;
    LblStatus: Label;
    Split: Split;
    SideBar: Panel;
    CmbView: ComboBox;
    FileTree: TreeView;
    ChangesBox: Panel;
    ChangeTable: TableView;
    LblChanges: Label;
    TxtCommit: TextBox;
    CommitRow: Panel;
    BtnChStage: Button;
    BtnChCommit: Button;
    RightSplit: Split;
    WorkArea: Split;
    EditorBox: Panel;
    ReloadBar: Panel;
    ImgReload: Image;
    LblReload: Label;
    BtnTakeDisk: Button;
    BtnReloadHide: Button;
    Tabs: Notebook;
    TabActions: Button;
    FindBar: Panel;
    FindRow: Panel;
    FindText: TextBox;
    LblFindCount: Label;
    BtnFindPrev: Button;
    BtnFindNext: Button;
    ChkFindCase: CheckButton;
    ChkFindWord: CheckButton;
    ChkFindRegex: CheckButton;
    BtnFindClose: Button;
    ReplaceRow: Panel;
    ReplaceText: TextBox;
    BtnReplace: Button;
    BtnReplaceAll: Button;
    SidePanel: Panel;
    SideTabs: Switcher;
    PropBox: Panel;
    PropDesignRow: Panel;
    PropDesignLabel: Label;
    PropDesign: Switch;
    PropFind: TextBox;
    PropGrid: RowList;
    EventsBox: Panel;
    EventList: RowList;
    ControlsBox: Panel;
    SideSplit: Split;
    Palette: Notebook;
    WidgetTree: TreeView;
    DesignBar: Panel;
    BtnDelCtl: Button;
    BtnRaise: Button;
    BtnLower: Button;
    OutlineBox: Panel;
    LblOutline: Label;
    OutlineList: ListBox;
    ConsoleBox: Notebook;
    LogView: TextEditor;
    DebugPage: Panel;
    DebugBox: Split;
    StackBox: Panel;
    LblStack: Label;
    StackList: RowList;
    LocalBox: Panel;
    LblLocals: Label;
    LocalList: RowList;
    ImmediateRow: Panel;
    TxtImmediate: TextBox;
    BtnWatch: Button;
    ProblemView: TableView;
    MnuFile: MenuItem;
    MnuNewProject: MenuItem;
    MnuNewForm: MenuItem;
    MnuNewComponent: MenuItem;
    MnuNewModule: MenuItem;
    MnuOpen: MenuItem;
    MnuRecent: MenuItem;
    MnuReload: MenuItem;
    MnuCloseTab: MenuItem;
    MnuRename: MenuItem;
    MnuDelete: MenuItem;
    MnuSave: MenuItem;
    MnuSaveAll: MenuItem;
    MnuRecovery: MenuItem;
    MnuQuit: MenuItem;
    MnuEditMenu: MenuItem;
    MnuUndo: MenuItem;
    MnuRedo: MenuItem;
    MnuCut: MenuItem;
    MnuCopy: MenuItem;
    MnuPaste: MenuItem;
    MnuDuplicate: MenuItem;
    MnuFind: MenuItem;
    MnuReplace: MenuItem;
    MnuFindAll: MenuItem;
    MnuFindNext: MenuItem;
    MnuFindPrev: MenuItem;
    MnuComplete: MenuItem;
    MnuGoto: MenuItem;
    MnuGotoSymbol: MenuItem;
    MnuGotoFile: MenuItem;
    MnuCommands: MenuItem;
    MnuProject: MenuItem;
    MnuRun: MenuItem;
    MnuStop: MenuItem;
    MnuStrict: MenuItem;
    MnuLaunch: MenuItem;
    MnuLaunchEdit: MenuItem;
    MnuTranslations: MenuItem;
    MnuTranslationNew: MenuItem;
    MnuTranslationEditor: MenuItem;
    MnuTidy: MenuItem;
    MnuExport: MenuItem;
    MnuAppInstall: MenuItem;
    MnuMetainfo: MenuItem;
    MnuCheck: MenuItem;
    MnuProjectSettings: MenuItem;
    MnuGitMenu: MenuItem;
    MnuGitRefresh: MenuItem;
    MnuGitChanges: MenuItem;
    MnuGitLog: MenuItem;
    MnuGitBranch: MenuItem;
    MnuGitNewBranch: MenuItem;
    MnuGitDropBranch: MenuItem;
    MnuGitFetch: MenuItem;
    MnuGitPull: MenuItem;
    MnuGitPush: MenuItem;
    MnuGitInit: MenuItem;
    MnuGitClone: MenuItem;
    MnuDebugMenu: MenuItem;
    MnuDebug: MenuItem;
    MnuPause: MenuItem;
    MnuStepInto: MenuItem;
    MnuStepOver: MenuItem;
    MnuStepOut: MenuItem;
    MnuBreakpoint: MenuItem;
    MnuStopThrow: MenuItem;
    MnuFormMenu: MenuItem;
    MnuMenus: MenuItem;
    MnuAdd: MenuItem;
    MnuHandler: MenuItem;
    MnuAlignLeft: MenuItem;
    MnuAlignRight: MenuItem;
    MnuAlignTop: MenuItem;
    MnuAlignBottom: MenuItem;
    MnuSameWidth: MenuItem;
    MnuSameHeight: MenuItem;
    MnuSpreadH: MenuItem;
    MnuSpreadV: MenuItem;
    MnuTabOrder: MenuItem;
    MnuHelp: MenuItem;
    MnuReference: MenuItem;
    MnuAbout: MenuItem;
    ActDelCtl: Action;
    ActRaise: Action;
    ActLower: Action;
    ActRenameCtl: Action;
}

interface MenuForm {
    PnlContent: Panel;
    PnlBody: Panel;
    PnlTree: Panel;
    LblTree: Label;
    Tree: TreeView;
    BtnGrid: Grid;
    BtnItem: Button;
    BtnSubmenu: Button;
    BtnSeparator: Button;
    BtnUp: Button;
    BtnDown: Button;
    BtnDelete: Button;
    PnlItem: Panel;
    LblText: Label;
    TxtText: TextBox;
    LblName: Label;
    TxtName: TextBox;
    LblShortcut: Label;
    TxtShortcut: TextBox;
    ChkDynamic: CheckButton;
    ChkCheck: CheckButton;
    ChkRadio: CheckButton;
    LblHint: Label;
    PnlButtons: Panel;
    BtnCancel: Button;
    BtnOk: Button;
}

interface MetainfoForm {
    PnlContent: Panel;
    LblWhere: Label;
    Fields: Grid;
    LblId: Label;
    TxtId: TextBox;
    LblName: Label;
    TxtName: TextBox;
    LblSummary: Label;
    TxtSummary: TextBox;
    LblDevId: Label;
    TxtDevId: TextBox;
    LblDevName: Label;
    TxtDevName: TextBox;
    LblMetaLic: Label;
    TxtMetaLic: TextBox;
    LblProjLic: Label;
    TxtProjLic: TextBox;
    LblHome: Label;
    TxtHome: TextBox;
    LblBug: Label;
    TxtBug: TextBox;
    LblCats: Label;
    TxtCats: TextBox;
    LblDesc: Label;
    TxtDesc: TextEditor;
    LblProblem: Label;
    PnlButtons: Panel;
    BtnCancel: Button;
    BtnSave: Button;
}

interface NewProjectForm {
    PnlContent: Panel;
    Fields: Grid;
    LblName: Label;
    TxtName: TextBox;
    LblId: Label;
    TxtId: TextBox;
    LblKind: Label;
    CmbKind: ComboBox;
    LblDesc: Label;
    TxtDesc: TextBox;
    LblBase: Label;
    TxtBase: TextBox;
    LblHint: Label;
    PnlButtons: Panel;
    BtnCancel: Button;
    BtnCreate: Button;
}

interface PoForm {
    Bar: Panel;
    LblCount: Label;
    ChkTodo: CheckButton;
    Body: Split;
    LstEntries: ListBox;
    Pane: Panel;
    LblSourceCaption: Label;
    LblSource: Label;
    Forms: Panel;
    ChkFuzzy: CheckButton;
    LblRefs: Label;
    Buttons: Panel;
    BtnSave: Button;
    BtnClose: Button;
}

interface ProjectForm {
    LblPrName: Label;
    TxtPrName: TextBox;
    LblPrVersion: Label;
    TxtPrVersion: TextBox;
    LblPrId: Label;
    TxtPrId: TextBox;
    LblPrStartup: Label;
    CmbPrKind: ComboBox;
    CmbPrStartup: ComboBox;
    TxtPrMain: TextBox;
    LblPrDesc: Label;
    TxtPrDesc: TextBox;
    LblPrUses: Label;
    LstPrUses: RowList;
    LblPrUsesHint: Label;
    LblPrOrder: Label;
    LstPrSources: ListBox;
    BtnPrUp: Button;
    BtnPrDown: Button;
    BtnPrDecide: Button;
    LblPrHint: Label;
    BtnPrCancel: Button;
    BtnPrOk: Button;
}

interface QuickForm {
    TxtFind: TextBox;
    List: RowList;
    LblCount: Label;
    BtnCancel: Button;
    BtnOk: Button;
}

interface SearchForm {
    Head: Panel;
    TermRow: Panel;
    TxtTerm: TextBox;
    BtnFind: Button;
    OptionRow: Panel;
    ChkCase: CheckButton;
    ChkWord: CheckButton;
    ChkRegex: CheckButton;
    LblFiles: Label;
    CboFiles: ComboBox;
    LblCount: Label;
    Results: TreeView;
    Buttons: Panel;
    BtnClose: Button;
}

interface StyleForm {
    TxtFind: TextBox;
    List: RowList;
    LblChosen: Label;
    BtnNew: Button;
    BtnEdit: Button;
    BtnCancel: Button;
    BtnOk: Button;
}

interface SymbolForm {
    TxtFind: TextBox;
    List: RowList;
    LblCount: Label;
    BtnCancel: Button;
    BtnOk: Button;
}

interface TabOrderForm {
    LblWhich: Label;
    LstOrder: ListBox;
    BtnUp: Button;
    BtnDown: Button;
    BtnCancel: Button;
    BtnOk: Button;
}
