/*
 * Bintana's own surface, for an editor that is not the Bintana IDE.
 *
 * GENERATED by tools/typings -- regenerate with tests/typings.sh and do
 * not edit. tests/api.sh fails when this file and the runtime disagree.
 */

declare class Widget {
    AcceptDrop: boolean;
    AcceptFiles: boolean;
    Action: string;
    Background: string;
    Border: string;
    ColumnSpan: number;
    Cursor: string;
    DragData: string;
    Enabled: boolean;
    Expand: boolean;
    Focusable: boolean;
    Font: string;
    FontScale: number;
    Foreground: string;
    HAlign: string;
    HExpand: boolean;
    Height: number;
    Margin: number;
    Menu: any;
    MinHeight: number;
    MinWidth: number;
    Name: string;
    Opacity: number;
    Padding: string;
    Radius: string;
    Shadow: string;
    Shortcut: string;
    Style: string;
    TabIndex: number;
    Tooltip: string;
    VAlign: string;
    VExpand: boolean;
    Visible: boolean;
    Width: number;
    X: number;
    Y: number;
    __declared: any;
    readonly Dark: boolean;
    readonly Focused: boolean;
    Apply(...values: any[]): any;
    Bounds(...values: any[]): any;
    CssNode(...values: any[]): any;
    Declared(...values: any[]): any;
    Delete(...values: any[]): any;
    DesignValue(...values: any[]): any;
    Dump(...values: any[]): any;
    Emit(...values: any[]): any;
    EventNames(...values: any[]): any;
    Fill(...values: any[]): any;
    Hide(...values: any[]): any;
    Lower(...values: any[]): any;
    Move(...values: any[]): any;
    On(...values: any[]): any;
    OriginIn(...values: any[]): any;
    PopupMenu(...values: any[]): any;
    PropertyNames(...values: any[]): any;
    PropertyOptions(...values: any[]): any;
    Raise(...values: any[]): any;
    Remove(...values: any[]): any;
    Resize(...values: any[]): any;
    Serialize(...values: any[]): any;
    SetDesign(...values: any[]): any;
    SetFocus(...values: any[]): any;
    SetItem(...values: any[]): any;
    Show(...values: any[]): any;
    SizeRequest(...values: any[]): any;
    StyleRule(...values: any[]): any;
    TextProperties(...values: any[]): any;
    static New(type: string): Widget;
    static Types(): string[];
    static Available(type: string): boolean;
    static TypeName(ctor: any): string;
}

declare class Container extends Widget { }
declare class Control extends Widget { }
declare class Editor extends Widget { }

declare class Form extends Widget {
    Anchored: boolean;
    Arrangement: string;
    FullScreen: boolean;
    HideOnClose: boolean;
    Homogeneous: boolean;
    Icon: string;
    Maximized: boolean;
    Modal: boolean;
    Resizable: boolean;
    Spacing: number;
    Text: string;
    readonly CancelButton: any;
    readonly Children: any[];
    readonly DefaultButton: any;
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Center(...values: any[]): any;
    Clear(...values: any[]): any;
    Close(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    Minimize(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
    SaveForm(...values: any[]): any;
}
declare class Panel extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Spacing: number;
    readonly Children: any[];
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class Component extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Spacing: number;
    readonly Children: any[];
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class Label extends Widget {
    Alignment: string;
    Ellipsize: boolean;
    Lines: number;
    Markup: boolean;
    Selectable: boolean;
    Text: string;
    Wrap: boolean;
}
declare class Button extends Widget {
    Cancel: boolean;
    Default: boolean;
    Icon: string;
    Text: string;
    Click(...values: any[]): any;
}
declare class Image extends Widget {
    File: string;
    Icon: string;
    Size: number;
    LoadBytes(...values: any[]): any;
}
declare class Separator extends Widget {
    Orientation: string;
}
declare class TextBox extends Widget {
    ActivatesDefault: boolean;
    Alignment: string;
    Icon: string;
    MaxLength: number;
    Password: boolean;
    Placeholder: string;
    Purpose: string;
    ReadOnly: boolean;
    Text: string;
    readonly SelectedText: string;
    Select(...values: any[]): any;
    SelectAll(...values: any[]): any;
}
declare class CheckButton extends Widget {
    Active: boolean;
    Group: string;
    Text: string;
}
declare class Switch extends Widget {
    Active: boolean;
}
declare class ListBox extends Widget {
    ActivateOnSingleClick: boolean;
    Index: number;
    Items: any[];
    MultiSelect: boolean;
    readonly Count: number;
    readonly Selection: any[];
    readonly Text: string;
    Activate(...values: any[]): any;
    Add(...values: any[]): any;
    Clear(...values: any[]): any;
    Deselect(...values: any[]): any;
    DeselectAll(...values: any[]): any;
    Select(...values: any[]): any;
    SelectAll(...values: any[]): any;
}
declare class ComboBox extends Widget {
    Index: number;
    Items: any[];
    Text: string;
    readonly Count: number;
    Add(...values: any[]): any;
    Clear(...values: any[]): any;
}
declare class SpinBox extends Widget {
    Decimals: number;
    Max: number;
    Min: number;
    Numeric: boolean;
    Step: number;
    Value: number;
    Wrap: boolean;
}
declare class Picture extends Widget {
    File: string;
    Fit: string;
    Zoom: number;
    readonly SourceHeight: number;
    readonly SourceWidth: number;
    LoadBytes(...values: any[]): any;
}
declare class Spinner extends Widget {
    Active: boolean;
}
declare class LinkButton extends Widget {
    Text: string;
    Uri: string;
}
declare class LevelBar extends Widget {
    Max: number;
    Min: number;
    Mode: string;
    Orientation: string;
    Value: number;
}
declare class ToggleButton extends Widget {
    Active: boolean;
    Icon: string;
    Text: string;
    Click(...values: any[]): any;
}
declare class ProgressBar extends Widget {
    Orientation: string;
    ShowText: boolean;
    Text: string;
    Value: number;
    Pulse(...values: any[]): any;
}
declare class Slider extends Widget {
    Decimals: number;
    Inverted: boolean;
    Max: number;
    Min: number;
    Orientation: string;
    ShowValue: boolean;
    Step: number;
    Value: number;
    ValuePosition: string;
    ClearMarks(...values: any[]): any;
    Mark(...values: any[]): any;
}
declare class DatePicker extends Widget {
    Format: string;
    Placeholder: string;
    Value: string;
}
declare class Calendar extends Widget {
    ShowDayNames: boolean;
    ShowHeading: boolean;
    ShowWeekNumbers: boolean;
    Value: string;
    readonly Marks: any[];
    ClearMarks(...values: any[]): any;
    Mark(...values: any[]): any;
    Unmark(...values: any[]): any;
}
declare class ColorButton extends Widget {
    Value: string;
}
declare class FontButton extends Widget {
    Value: string;
}
declare class Split extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Grows: string;
    Homogeneous: boolean;
    Position: number;
    Spacing: number;
    WideHandle: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class Frame extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Spacing: number;
    Text: string;
    readonly Children: any[];
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class Expander extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Expanded: boolean;
    Homogeneous: boolean;
    Spacing: number;
    Text: string;
    readonly Children: any[];
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class Overlay extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Spacing: number;
    readonly Children: any[];
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class RowList extends Widget {
    ActivateOnSingleClick: boolean;
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Index: number;
    MultiSelect: boolean;
    Spacing: number;
    readonly Children: any[];
    readonly Count: number;
    readonly Placement: string;
    readonly Selection: any[];
    Activate(...values: any[]): any;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    Deselect(...values: any[]): any;
    DeselectAll(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Refilter(...values: any[]): any;
    Reorder(...values: any[]): any;
    Select(...values: any[]): any;
    SelectAll(...values: any[]): any;
}
declare class Scroller extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    ScrollX: number;
    ScrollY: number;
    Scrollbars: string;
    Spacing: number;
    readonly Children: any[];
    readonly Placement: string;
    readonly ScrollMaxX: number;
    readonly ScrollMaxY: number;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class AspectFrame extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Ratio: string;
    Spacing: number;
    readonly Children: any[];
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class Flow extends Widget {
    Anchored: boolean;
    Arrangement: string;
    ColumnSpacing: number;
    Homogeneous: boolean;
    MaxPerLine: number;
    MinPerLine: number;
    RowSpacing: number;
    Spacing: number;
    readonly Children: any[];
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class Grid extends Widget {
    Anchored: boolean;
    Arrangement: string;
    ColumnSpacing: number;
    Columns: number;
    Homogeneous: boolean;
    RowSpacing: number;
    Spacing: number;
    readonly Children: any[];
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class Notebook extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Current: number;
    Homogeneous: boolean;
    Spacing: number;
    Strip: string;
    Tabs: any[];
    readonly Children: any[];
    readonly Count: number;
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    Append(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    GetAction(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
    SetAction(...values: any[]): any;
    SetTabLabel(...values: any[]): any;
}
declare class Switcher extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Current: number;
    Homogeneous: boolean;
    Spacing: number;
    Strip: string;
    Tabs: any[];
    readonly Children: any[];
    readonly Count: number;
    readonly Placement: string;
    Add(...values: any[]): any;
    AddNode(...values: any[]): any;
    Append(...values: any[]): any;
    BuildChildren(...values: any[]): any;
    Clear(...values: any[]): any;
    ContainerAt(...values: any[]): any;
    FocusNext(...values: any[]): any;
    FocusPrevious(...values: any[]): any;
    LocalPoint(...values: any[]): any;
    PickAt(...values: any[]): any;
    Reorder(...values: any[]): any;
}
declare class DrawingArea extends Widget {
    Redraw(...values: any[]): any;
    Save(...values: any[]): any;
    SavePdf(...values: any[]): any;
    ToPng(...values: any[]): any;
}
declare class TextEditor extends Widget {
    Modified: boolean;
    ReadOnly: boolean;
    ScrollX: number;
    ScrollY: number;
    Text: string;
    Wrap: boolean;
    readonly CanRedo: boolean;
    readonly CanUndo: boolean;
    readonly Column: number;
    readonly Line: number;
    readonly ScrollMaxX: number;
    readonly ScrollMaxY: number;
    readonly Selection: string;
    Append(...values: any[]): any;
    Clear(...values: any[]): any;
    GotoLine(...values: any[]): any;
    Insert(...values: any[]): any;
    Redo(...values: any[]): any;
    Select(...values: any[]): any;
    Undo(...values: any[]): any;
}
declare class SourceEditor extends Widget {
    Completion: boolean;
    CompletionTitle: string;
    Language: string;
    Modified: boolean;
    ReadOnly: boolean;
    ScrollX: number;
    ScrollY: number;
    ShowLineNumbers: boolean;
    ShowMarks: boolean;
    Text: string;
    Theme: string;
    Wrap: boolean;
    readonly CanRedo: boolean;
    readonly CanUndo: boolean;
    readonly Column: number;
    readonly Line: number;
    readonly MatchIndex: number;
    readonly Matches: number;
    readonly ScrollMaxX: number;
    readonly ScrollMaxY: number;
    readonly Selection: string;
    Append(...values: any[]): any;
    Clear(...values: any[]): any;
    ClearMarks(...values: any[]): any;
    FindNext(...values: any[]): any;
    FindPrevious(...values: any[]): any;
    GotoLine(...values: any[]): any;
    Insert(...values: any[]): any;
    Mark(...values: any[]): any;
    Marks(...values: any[]): any;
    Redo(...values: any[]): any;
    Replace(...values: any[]): any;
    ReplaceAll(...values: any[]): any;
    Search(...values: any[]): any;
    Select(...values: any[]): any;
    ShowCompletion(...values: any[]): any;
    Undo(...values: any[]): any;
    Unmark(...values: any[]): any;
}
declare class Terminal extends Widget {
    LinkPattern: string;
    ScrollbackLines: number;
    readonly Available: boolean;
    readonly Running: boolean;
    readonly Text: string;
    Clear(...values: any[]): any;
    Feed(...values: any[]): any;
    Kill(...values: any[]): any;
    Run(...values: any[]): any;
    Stop(...values: any[]): any;
}
declare class TreeView extends Widget {
    AutoExpand: boolean;
    Key: string;
    readonly Count: number;
    readonly Text: string;
    Add(...values: any[]): any;
    Clear(...values: any[]): any;
    CollapseAll(...values: any[]): any;
    CollapseNode(...values: any[]): any;
    Exists(...values: any[]): any;
    ExpandAll(...values: any[]): any;
    ExpandNode(...values: any[]): any;
    Expanded(...values: any[]): any;
    SetIcon(...values: any[]): any;
    SetText(...values: any[]): any;
}
declare class TableView extends Widget {
    AutoExpand: boolean;
    ColumnLines: boolean;
    Columns: any[];
    Count: number;
    Index: number;
    Key: string;
    MultiSelect: boolean;
    RowLines: boolean;
    Sortable: boolean;
    readonly Selection: any[];
    Add(...values: any[]): any;
    Cell(...values: any[]): any;
    Clear(...values: any[]): any;
    CollapseAll(...values: any[]): any;
    CollapseNode(...values: any[]): any;
    Deselect(...values: any[]): any;
    DeselectAll(...values: any[]): any;
    Exists(...values: any[]): any;
    ExpandAll(...values: any[]): any;
    ExpandNode(...values: any[]): any;
    Expanded(...values: any[]): any;
    Row(...values: any[]): any;
    Select(...values: any[]): any;
    SelectAll(...values: any[]): any;
    SetCell(...values: any[]): any;
    SetIcon(...values: any[]): any;
    SortBy(...values: any[]): any;
    SortColumn(...values: any[]): any;
}
declare class Video extends Widget {
    Fit: string;
    Latency: number;
    Loop: boolean;
    Muted: boolean;
    Password: string;
    Uri: string;
    User: string;
    Volume: number;
    readonly Available: boolean;
    readonly Buffering: number;
    readonly Duration: number;
    readonly Playing: boolean;
    readonly Position: number;
    readonly Seekable: boolean;
    readonly SourceHeight: number;
    readonly SourceWidth: number;
    Pause(...values: any[]): any;
    Play(...values: any[]): any;
    Save(...values: any[]): any;
    Seek(...values: any[]): any;
    Stop(...values: any[]): any;
}

declare class Action {
    Click(...values: any[]): any;
    Enabled: any;
    EventNames(...values: any[]): any;
    Icon: any;
    Name: any;
    PropertyNames(...values: any[]): any;
    Text: any;
}

declare const Application: {
    Arguments: any;
    CheckSource(...values: any[]): any;
    ConfigDirectory: any;
    DecorationLayout: any;
    Directory: any;
    Executable: any;
    HasCommand(...values: any[]): any;
    HasIcon(...values: any[]): any;
    Icons(...values: any[]): any;
    Libraries(...values: any[]): any;
    LibraryPath(...values: any[]): any;
    Name: any;
    Quit(...values: any[]): any;
    Version: any;
};

declare class AudioPlayer {
    Buffering: any;
    Duration: any;
    Latency: any;
    Loop: any;
    Muted: any;
    OnEnded: any;
    OnError: any;
    Password: any;
    Pause(...values: any[]): any;
    Play(...values: any[]): any;
    Playing: any;
    Position: any;
    Seek(...values: any[]): any;
    Seekable: any;
    Stop(...values: any[]): any;
    Uri: any;
    User: any;
    Volume: any;
}

declare class Bytes {
    At(...values: any[]): any;
    Concat(...values: any[]): any;
    Equals(...values: any[]): any;
    Length: any;
    Slice(...values: any[]): any;
    ToBase64(...values: any[]): any;
    ToHex(...values: any[]): any;
    ToText(...values: any[]): any;
    toJSON(...values: any[]): any;
    toString(...values: any[]): any;
}

declare const Clipboard: {
    Copy(...values: any[]): any;
    Paste(...values: any[]): any;
};

declare class Connection {
    Close(...values: any[]): any;
    Columns(...values: any[]): any;
    Dialect: any;
    Execute(...values: any[]): any;
    Open: any;
    Path: any;
    Query(...values: any[]): any;
    Script(...values: any[]): any;
    Tables: any;
    Transaction(...values: any[]): any;
}

declare class Day {
    Add(...values: any[]): any;
    Between(...values: any[]): any;
    Today: any;
    Weekday(...values: any[]): any;
}

declare class Decimal {
    Abs(...values: any[]): any;
    IsExact: any;
    Number(...values: any[]): any;
    Round(...values: any[]): any;
    Scale: any;
    Sign: any;
    Trim(...values: any[]): any;
    toJSON(...values: any[]): any;
    toString(...values: any[]): any;
}

declare const Desktop: {
    CacheDirectory: any;
    ConfigDirectory: any;
    DataDirectory: any;
    Entries: any;
};

declare const Dialog: {
    Color(...values: any[]): any;
    OpenFile(...values: any[]): any;
    SaveFile(...values: any[]): any;
    SelectFolder(...values: any[]): any;
};

declare const Dictionary: {
    Count(...values: any[]): any;
    Entries(...values: any[]): any;
    Has(...values: any[]): any;
    Keys(...values: any[]): any;
    Values(...values: any[]): any;
};

declare const Directory: {
    Copy(...values: any[]): any;
    Delete(...values: any[]): any;
    DeleteTree(...values: any[]): any;
    Files(...values: any[]): any;
    Folders(...values: any[]): any;
    List(...values: any[]): any;
    Make(...values: any[]): any;
};

declare const Environment: {
    CurrentDirectory: any;
    Get(...values: any[]): any;
    HasDisplay: any;
    HomeDirectory: any;
    HostName: any;
    OS: any;
    OSVersion: any;
    ProcessId: any;
    ProcessorCount: any;
    Set(...values: any[]): any;
    TempDirectory: any;
    UserName: any;
    Variables: any;
};

declare const File: {
    Absolute(...values: any[]): any;
    BaseName(...values: any[]): any;
    Copy(...values: any[]): any;
    Delete(...values: any[]): any;
    Directory(...values: any[]): any;
    Exists(...values: any[]): any;
    Extension(...values: any[]): any;
    Hash(...values: any[]): any;
    Info(...values: any[]): any;
    IsDir(...values: any[]): any;
    Join(...values: any[]): any;
    Load(...values: any[]): any;
    LoadBytes(...values: any[]): any;
    LoadJson(...values: any[]): any;
    Name(...values: any[]): any;
    Open(...values: any[]): any;
    Rename(...values: any[]): any;
    Save(...values: any[]): any;
    SaveBytes(...values: any[]): any;
    SaveJson(...values: any[]): any;
    Trash(...values: any[]): any;
    Watch(...values: any[]): any;
};

declare const Hash: {
    Md5(...values: any[]): any;
    Sha1(...values: any[]): any;
    Sha256(...values: any[]): any;
    Sha512(...values: any[]): any;
};

declare const Http: {
    Client(...values: any[]): any;
    Delete(...values: any[]): any;
    DeleteWait(...values: any[]): any;
    Get(...values: any[]): any;
    GetWait(...values: any[]): any;
    Head(...values: any[]): any;
    HeadWait(...values: any[]): any;
    Patch(...values: any[]): any;
    PatchWait(...values: any[]): any;
    Post(...values: any[]): any;
    PostWait(...values: any[]): any;
    Put(...values: any[]): any;
    PutWait(...values: any[]): any;
    Request(...values: any[]): any;
    RequestWait(...values: any[]): any;
    Server(...values: any[]): any;
    Stream(...values: any[]): any;
};

declare class HttpClient {
    Auth: any;
    BaseUrl: any;
    Cookies: any;
    Delete(...values: any[]): any;
    DeleteWait(...values: any[]): any;
    FollowRedirects: any;
    Get(...values: any[]): any;
    GetWait(...values: any[]): any;
    Head(...values: any[]): any;
    HeadWait(...values: any[]): any;
    Headers: any;
    IdleTimeout: any;
    Language: any;
    Log: any;
    MaxConns: any;
    MaxPerHost: any;
    Patch(...values: any[]): any;
    PatchWait(...values: any[]): any;
    Post(...values: any[]): any;
    PostWait(...values: any[]): any;
    Proxy: any;
    Put(...values: any[]): any;
    PutWait(...values: any[]): any;
    Request(...values: any[]): any;
    RequestWait(...values: any[]): any;
    Stream(...values: any[]): any;
    Timeout: any;
    UserAgent: any;
}

declare class HttpRequest {
    Answer(...values: any[]): any;
    Multipart(...values: any[]): any;
}

declare class HttpServer {
    Allow: any;
    Auth: any;
    Host: any;
    Port: any;
    Request: any;
    Running: any;
    ServerName: any;
    Start(...values: any[]): any;
    Stop(...values: any[]): any;
    Tls: any;
    Url: any;
}

declare const Locale: {
    Available: any;
    Compare(...values: any[]): any;
    Context(...values: any[]): any;
    Currency(...values: any[]): any;
    Current: any;
    Date(...values: any[]): any;
    DecimalPoint: any;
    Matches(...values: any[]): any;
    Number(...values: any[]): any;
    Plural(...values: any[]): any;
    Read(...values: any[]): any;
    Text(...values: any[]): any;
};

declare const Lock: {
    Hold(...values: any[]): any;
};

declare const Logger: {
    Debug(...values: any[]): any;
    Error(...values: any[]): any;
    Info(...values: any[]): any;
    Level: any;
    Target: any;
    Warning(...values: any[]): any;
};

declare class MenuItem {
    Click(...values: any[]): any;
    Enabled: any;
    EventNames(...values: any[]): any;
    Items: any;
    Name: any;
    PropertyNames(...values: any[]): any;
    Value: any;
}

declare const Message: {
    Error(...values: any[]): any;
    Info(...values: any[]): any;
    Warning(...values: any[]): any;
};

declare class Multipart {
    Field(...values: any[]): any;
    File(...values: any[]): any;
    Length: any;
    Part(...values: any[]): any;
}

declare class Painter {
    Antialias: any;
    Arc(...values: any[]): any;
    ArcNegative(...values: any[]): any;
    Clip(...values: any[]): any;
    ClipRectangle(...values: any[]): any;
    ClosePath(...values: any[]): any;
    Color: any;
    CurveTo(...values: any[]): any;
    Dark: any;
    Fill(...values: any[]): any;
    Font: any;
    Foreground: any;
    Image(...values: any[]): any;
    LineCap: any;
    LineDash: any;
    LineJoin: any;
    LineTo(...values: any[]): any;
    LineWidth: any;
    MoveTo(...values: any[]): any;
    Polygon(...values: any[]): any;
    Polyline(...values: any[]): any;
    Pop(...values: any[]): any;
    Push(...values: any[]): any;
    Rectangle(...values: any[]): any;
    Rotate(...values: any[]): any;
    Scale(...values: any[]): any;
    Stroke(...values: any[]): any;
    Text(...values: any[]): any;
    TextHeight(...values: any[]): any;
    TextWidth(...values: any[]): any;
    Translate(...values: any[]): any;
}

declare const Printer: {
    Default: any;
    Names: any;
    Papers: any;
    Send(...values: any[]): any;
    ToFile(...values: any[]): any;
};

declare const Screen: {
    Height: any;
    Monitors(...values: any[]): any;
    Scale: any;
    Width: any;
};

declare const Settings: {
    Clear(...values: any[]): any;
    Delete(...values: any[]): any;
    Get(...values: any[]): any;
    Has(...values: any[]): any;
    Keys(...values: any[]): any;
    Path: any;
    Set(...values: any[]): any;
};

declare class Task {
    Report(...values: any[]): any;
    Start(...values: any[]): any;
    Stop(...values: any[]): any;
    Stopping: any;
}

declare const Text: {
    Bounds(...values: any[]): any;
    Escape(...values: any[]): any;
    Font: any;
    Height(...values: any[]): any;
    IndexAt(...values: any[]): any;
    Lines(...values: any[]): any;
    Size(...values: any[]): any;
    Width(...values: any[]): any;
};

declare const Time: {
    Add(...values: any[]): any;
    Between(...values: any[]): any;
    Now: any;
    Seconds(...values: any[]): any;
};

declare class Timer {
    constructor(milliseconds?: number, repeat?: boolean);
    Interval: number;
    Repeat: boolean;
    Enabled: boolean;
    Tick: any;
    Start(): void;
    Stop(): void;
}

declare class Stopwatch {
    constructor();
    Elapsed: number;
    Start(): void;
    Stop(): void;
    Reset(): void;
}

declare class Regex {
    constructor(pattern: string, options?: { IgnoreCase?: boolean; Multiline?: boolean; DotAll?: boolean });
    static Escape(text: string): string;
    IsMatch(text: string): boolean;
    Match(text: string): any;
    Matches(text: string): any[];
    Replace(text: string, by: string): string;
    Split(text: string): string[];
}

/*
 * A value and not a class, which is the one declaration here that is shaped by
 * TypeScript rather than by Bintana: `Record<K, V>` is a type alias in
 * `lib.es5.d.ts`, so `declare class Record` writes a *type* of that name too
 * and both files lose -- "Duplicate identifier 'Record'", measured. A const
 * with a construct signature declares the value alone, so `new Record()` is
 * this one and `Record<string, number>` stays TypeScript's.
 */
declare const Record: {
    new (fields?: any): any;
    prototype: any;
};

declare const Field: any;
declare const Database: any;
declare const Exec: any;
declare const Table: any;
declare const BTA_VERSION: string;

declare function Namespace(path: string): any;
declare function print(...values: any[]): void;
declare function monotonic(): number;
declare function setTimeout(fn: () => void, ms?: number): number;
declare function clearTimeout(id: number): void;
declare function setInterval(fn: () => void, ms?: number): number;
declare function clearInterval(id: number): void;
