/*
 * Bintana's own surface, for an editor that is not the Bintana IDE.
 *
 * GENERATED by tools/typings -- regenerate with tests/typings.sh and do
 * not edit. tests/api.sh fails when this file and the runtime disagree.
 */

declare class Widget {
    AcceptDrop: boolean;
    AcceptFiles: boolean;
    Action: string;
    Background: string;
    Border: string;
    ColumnSpan: number;
    Cursor: string;
    DragData: string;
    Enabled: boolean;
    Expand: boolean;
    Focusable: boolean;
    Font: string;
    FontScale: number;
    Foreground: string;
    HAlign: string;
    HExpand: boolean;
    Height: number;
    Margin: number;
    Menu: any;
    MinHeight: number;
    MinWidth: number;
    Name: string;
    Opacity: number;
    Padding: string;
    Radius: string;
    Shadow: string;
    Shortcut: string;
    Style: string;
    TabIndex: number;
    Tooltip: string;
    VAlign: string;
    VExpand: boolean;
    Width: number;
    X: number;
    Y: number;
    __declared: any;
    readonly Dark: boolean;
    readonly Focused: boolean;
    Apply(properties: any): any;
    Bounds(container?: any): any;
    CssNode(): any;
    Declared(name: any): any;
    Delete(): any;
    DesignValue(name: any): any;
    Dump(): any;
    Emit(event: any, ...args: any[]): any;
    EventNames(): any;
    Fill(...values: any[]): any;
    Hide(): any;
    Lower(): any;
    Move(x: any, y: any): any;
    On(event: any, fn: any): any;
    OriginIn(container: any): any;
    PopupMenu(x: any, y: any): any;
    PropertyNames(): any;
    PropertyOptions(name: any): any;
    Raise(): any;
    Remove(): any;
    Resize(width: any, height: any): any;
    Serialize(parentIsFixed: any): any;
    SetDesign(name: any, value: any): any;
    SetFocus(): any;
    SetItem(of: any, count: any): any;
    Show(): any;
    SizeRequest(): any;
    StyleRule(): any;
    TextProperties(): any;
    static New(type: string): Widget;
    static Types(): string[];
    static Available(type: string): boolean;
    static TypeName(ctor: any): string;
    static PropertyNames(type: string): string[];
    static Methods(type: string): string[];
    static EventNames(type: string): string[];
    static TextProperties(type: string): string[];
    static PropertyOptions(type: string, name: string): string[] | null;
    static Member(type: string, name: string): string;
    static Members(type: string): { Name: string; Kind: string }[];
    static Signature(type: string, name: string): string | null;
    static EventSignature(type: string, name: string): string | null;
}

declare class Container extends Widget { }
declare class Control extends Widget { }
declare class Editor extends Widget { }

declare class Form extends Widget {
    Anchored: boolean;
    Arrangement: string;
    FullScreen: boolean;
    HideOnClose: boolean;
    Homogeneous: boolean;
    Icon: string;
    Maximized: boolean;
    Modal: boolean;
    Resizable: boolean;
    Spacing: number;
    Text: string;
    Visible: boolean;
    readonly CancelButton: any;
    readonly Children: any[];
    readonly DefaultButton: any;
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Center(): any;
    Clear(): any;
    Close(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    Minimize(): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
    SaveForm(path: any): any;
}
declare class Panel extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Spacing: number;
    Visible: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class Component extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Spacing: number;
    Visible: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class Label extends Widget {
    Alignment: string;
    Ellipsize: boolean;
    Lines: number;
    Markup: boolean;
    Selectable: boolean;
    Text: string;
    Visible: boolean;
    Wrap: boolean;
}
declare class Button extends Widget {
    Cancel: boolean;
    Default: boolean;
    Icon: string;
    Text: string;
    Visible: boolean;
    Click(): any;
}
declare class Image extends Widget {
    File: string;
    Icon: string;
    Size: number;
    Visible: boolean;
    LoadBytes(bytes: any): any;
}
declare class Separator extends Widget {
    Orientation: string;
    Visible: boolean;
}
declare class TextBox extends Widget {
    ActivatesDefault: boolean;
    Alignment: string;
    Icon: string;
    MaxLength: number;
    Password: boolean;
    Placeholder: string;
    Purpose: string;
    ReadOnly: boolean;
    Text: string;
    Visible: boolean;
    readonly Offset: number;
    readonly Selection: string;
    Insert(text: any): any;
    Select(start: any, length: any): any;
    SelectAll(): any;
}
declare class CheckButton extends Widget {
    Active: boolean;
    Group: string;
    Text: string;
    Visible: boolean;
}
declare class Switch extends Widget {
    Active: boolean;
    Visible: boolean;
}
declare class ListBox extends Widget {
    ActivateOnSingleClick: boolean;
    Index: number;
    Items: any[];
    Key: string;
    MultiSelect: boolean;
    Visible: boolean;
    readonly Count: number;
    readonly Selection: any[];
    readonly Text: string;
    Activate(index: any): any;
    Add(text: any, key?: any): any;
    Clear(): any;
    Deselect(index: any): any;
    DeselectAll(): any;
    KeyAt(index: any): any;
    RemoveRow(index: any): any;
    Reveal(index: any): any;
    Select(index: any): any;
    SelectAll(): any;
    SetText(index: any, text: any): any;
}
declare class ComboBox extends Widget {
    Index: number;
    Items: any[];
    Key: string;
    Text: string;
    Visible: boolean;
    readonly Count: number;
    Add(text: any, key?: any): any;
    Clear(): any;
    KeyAt(index: any): any;
    RemoveRow(index: any): any;
    SetText(index: any, text: any): any;
}
declare class SpinBox extends Widget {
    Decimals: number;
    Max: number;
    Min: number;
    Numeric: boolean;
    Step: number;
    Value: number;
    Visible: boolean;
    Wrap: boolean;
}
declare class DecimalBox extends Widget {
    Currency: string;
    Decimals: number;
    Format: string;
    Group: boolean;
    Max: any;
    Min: any;
    Prefix: string;
    Step: any;
    Suffix: string;
    Value: any;
    Visible: boolean;
    Wrap: boolean;
    readonly Text: string;
}
declare class Picture extends Widget {
    File: string;
    Fit: string;
    Visible: boolean;
    Zoom: number;
    readonly SourceHeight: number;
    readonly SourceWidth: number;
    LoadBytes(bytes: any): any;
}
declare class Spinner extends Widget {
    Active: boolean;
    Visible: boolean;
}
declare class LinkButton extends Widget {
    Text: string;
    Uri: string;
    Visible: boolean;
}
declare class LevelBar extends Widget {
    Max: number;
    Min: number;
    Mode: string;
    Orientation: string;
    Value: number;
    Visible: boolean;
}
declare class ToggleButton extends Widget {
    Active: boolean;
    Icon: string;
    Text: string;
    Visible: boolean;
    Click(): any;
}
declare class ProgressBar extends Widget {
    Orientation: string;
    ShowText: boolean;
    Text: string;
    Value: number;
    Visible: boolean;
    Pulse(): any;
}
declare class Slider extends Widget {
    Decimals: number;
    Inverted: boolean;
    Max: number;
    Min: number;
    Orientation: string;
    ShowValue: boolean;
    Step: number;
    Value: number;
    ValuePosition: string;
    Visible: boolean;
    ClearMarks(): any;
    Mark(value: any, text?: any): any;
}
declare class DatePicker extends Widget {
    Format: string;
    Placeholder: string;
    Value: string;
    Visible: boolean;
}
declare class Calendar extends Widget {
    ShowDayNames: boolean;
    ShowHeading: boolean;
    ShowWeekNumbers: boolean;
    Value: string;
    Visible: boolean;
    readonly Marks: any[];
    ClearMarks(): any;
    Mark(date: any): any;
    Unmark(date: any): any;
}
declare class ColorButton extends Widget {
    Value: string;
    Visible: boolean;
}
declare class FontButton extends Widget {
    Value: string;
    Visible: boolean;
}
declare class Popover extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Arrow: boolean;
    Autohide: boolean;
    Homogeneous: boolean;
    Position: string;
    Spacing: number;
    readonly Children: any[];
    readonly Placement: string;
    readonly Visible: boolean;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    Close(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Popup(anchor: any): any;
    Reorder(child: any, index: any): any;
}
declare class Split extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Grows: string;
    Homogeneous: boolean;
    Position: number;
    Spacing: number;
    Visible: boolean;
    WideHandle: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class Frame extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Spacing: number;
    Text: string;
    Visible: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class Expander extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Expanded: boolean;
    Homogeneous: boolean;
    Spacing: number;
    Text: string;
    Visible: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class Overlay extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Spacing: number;
    Visible: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class RowList extends Widget {
    ActivateOnSingleClick: boolean;
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Index: number;
    MultiSelect: boolean;
    Spacing: number;
    Visible: boolean;
    readonly Children: any[];
    readonly Count: number;
    readonly Placement: string;
    readonly Selection: any[];
    Activate(index?: any): any;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    Deselect(index: any): any;
    DeselectAll(): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Refilter(): any;
    RemoveRow(index: any): any;
    Reorder(child: any, index: any): any;
    Reveal(index: any): any;
    Select(index: any): any;
    SelectAll(): any;
}
declare class Scroller extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    ScrollX: number;
    ScrollY: number;
    Scrollbars: string;
    Spacing: number;
    Visible: boolean;
    readonly Children: any[];
    readonly Placement: string;
    readonly ScrollMaxX: number;
    readonly ScrollMaxY: number;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class AspectFrame extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Homogeneous: boolean;
    Ratio: string;
    Spacing: number;
    Visible: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class Flow extends Widget {
    Anchored: boolean;
    Arrangement: string;
    ColumnSpacing: number;
    Homogeneous: boolean;
    MaxPerLine: number;
    MinPerLine: number;
    RowSpacing: number;
    Spacing: number;
    Visible: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class Grid extends Widget {
    Anchored: boolean;
    Arrangement: string;
    ColumnSpacing: number;
    Columns: number;
    Homogeneous: boolean;
    RowSpacing: number;
    Spacing: number;
    Visible: boolean;
    readonly Children: any[];
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    Reorder(child: any, index: any): any;
}
declare class Notebook extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Current: number;
    Homogeneous: boolean;
    Spacing: number;
    Strip: string;
    Tabs: any[];
    Visible: boolean;
    readonly Children: any[];
    readonly Count: number;
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    Append(child: any, label?: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    GetAction(where: any): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    RemovePage(index: any): any;
    Reorder(child: any, index: any): any;
    SetAction(control: any, where?: any): any;
    SetTabLabel(index: any, label: any): any;
}
declare class Switcher extends Widget {
    Anchored: boolean;
    Arrangement: string;
    Current: number;
    Homogeneous: boolean;
    Spacing: number;
    Strip: string;
    Tabs: any[];
    Visible: boolean;
    readonly Children: any[];
    readonly Count: number;
    readonly Placement: string;
    Add(widget: any): any;
    AddNode(node: any): any;
    Append(child: any, name?: any): any;
    BuildChildren(node: any): any;
    Clear(): any;
    ContainerAt(x: any, y: any, ignore?: any): any;
    FocusNext(): any;
    FocusPrevious(): any;
    LocalPoint(x: any, y: any, from: any): any;
    PickAt(x: any, y: any): any;
    RemovePage(index: any): any;
    Reorder(child: any, index: any): any;
}
declare class DrawingArea extends Widget {
    Visible: boolean;
    Redraw(): any;
    Save(path: any, width?: any, height?: any): any;
    SavePdf(path: any, width: any, height: any, pages?: any, before?: any): any;
    ToPng(width?: any, height?: any): any;
}
declare class TextEditor extends Widget {
    Modified: boolean;
    ReadOnly: boolean;
    ScrollX: number;
    ScrollY: number;
    Text: string;
    Visible: boolean;
    Wrap: boolean;
    readonly CanRedo: boolean;
    readonly CanUndo: boolean;
    readonly Column: number;
    readonly Line: number;
    readonly Offset: number;
    readonly ScrollMaxX: number;
    readonly ScrollMaxY: number;
    readonly Selection: string;
    Append(text: any): any;
    Clear(): any;
    GotoLine(line: any): any;
    Insert(text: any): any;
    LineOf(index: any): any;
    OffsetAt(line: any, column?: any): any;
    Redo(): any;
    Select(line: any, column?: any, length?: any): any;
    Undo(): any;
}
declare class SourceEditor extends Widget {
    Completion: boolean;
    CompletionTitle: string;
    Language: string;
    Modified: boolean;
    ReadOnly: boolean;
    ScrollX: number;
    ScrollY: number;
    ShowLineNumbers: boolean;
    ShowMarks: boolean;
    Text: string;
    Theme: string;
    Visible: boolean;
    Wrap: boolean;
    readonly CanRedo: boolean;
    readonly CanUndo: boolean;
    readonly Column: number;
    readonly Line: number;
    readonly MatchIndex: number;
    readonly Matches: number;
    readonly Offset: number;
    readonly ScrollMaxX: number;
    readonly ScrollMaxY: number;
    readonly Selection: string;
    Append(text: any): any;
    Clear(): any;
    ClearMarks(kind?: any): any;
    FindNext(): any;
    FindPrevious(): any;
    GotoLine(line: any): any;
    Insert(text: any): any;
    LineOf(index: any): any;
    Mark(line: any, kind: any, text?: any): any;
    Marks(kind?: any): any;
    OffsetAt(line: any, column?: any): any;
    Redo(): any;
    Replace(text: any): any;
    ReplaceAll(text: any): any;
    Search(text: any, options?: { CaseSensitive?: any; WholeWord?: any; Regex?: any }): any;
    Select(line: any, column?: any, length?: any): any;
    ShowCompletion(): any;
    Undo(): any;
    Unmark(line: any, kind?: any): any;
}
declare class Terminal extends Widget {
    LinkPattern: string;
    ScrollbackLines: number;
    Visible: boolean;
    readonly Available: boolean;
    readonly Running: boolean;
    readonly Text: string;
    Clear(): any;
    Feed(text: any): any;
    Kill(): any;
    Run(argv: any, workdir?: any): any;
    Stop(): any;
}
declare class TreeView extends Widget {
    ActivateOnSingleClick: boolean;
    AutoExpand: boolean;
    Key: string;
    Visible: boolean;
    readonly Count: number;
    readonly Text: string;
    Activate(index?: any): any;
    Add(key: any, text: any, parentKey?: any, icon?: any): any;
    Clear(): any;
    CollapseAll(): any;
    CollapseNode(key: any): any;
    Exists(key: any): any;
    ExpandAll(): any;
    ExpandNode(key: any): any;
    Expanded(key: any): any;
    RemoveNode(key: any): any;
    Reveal(index: any): any;
    SetIcon(key: any, name: any): any;
    SetText(key: any, text: any): any;
}
declare class TableView extends Widget {
    ActivateOnSingleClick: boolean;
    AutoExpand: boolean;
    ColumnLines: boolean;
    Columns: any[];
    Count: number;
    HeaderMenu: any;
    Index: number;
    Key: string;
    MultiSelect: boolean;
    RowLines: boolean;
    Sortable: boolean;
    Visible: boolean;
    readonly Selection: any[];
    Activate(index?: any): any;
    Add(values: any, options?: any): any;
    Cell(row: any, column: any): any;
    Clear(): any;
    CollapseAll(): any;
    CollapseNode(key: any): any;
    Deselect(index: any): any;
    DeselectAll(): any;
    Exists(key: any): any;
    ExpandAll(): any;
    ExpandNode(key: any): any;
    Expanded(key: any): any;
    RemoveNode(key: any): any;
    RemoveRow(index: any): any;
    Reveal(index: any): any;
    Row(index: any): any;
    Select(index: any): any;
    SelectAll(): any;
    SetCell(row: any, column: any, value: any): any;
    SetIcon(row: any, column: any, name: any): any;
    SortBy(column: any, ascending?: any, compare?: any): any;
    SortColumn(column: any, ascending?: any): any;
}
declare class Video extends Widget {
    Fit: string;
    Latency: number;
    Loop: boolean;
    Muted: boolean;
    Password: string;
    Uri: string;
    User: string;
    Visible: boolean;
    Volume: number;
    readonly Available: boolean;
    readonly Buffering: number;
    readonly Duration: number;
    readonly Playing: boolean;
    readonly Position: number;
    readonly Seekable: boolean;
    readonly SourceHeight: number;
    readonly SourceWidth: number;
    Pause(): any;
    Play(): any;
    Save(path: any): any;
    Seek(seconds: any): any;
    Stop(): any;
}

declare class Action {
    Click(...values: any[]): any;
    Enabled: any;
    EventNames(...values: any[]): any;
    Icon: any;
    Name: any;
    PropertyNames(...values: any[]): any;
    Text: any;
}

declare const Application: {
    Arguments: any;
    CheckSource(...values: any[]): any;
    ConfigDirectory: any;
    DecorationLayout: any;
    Directory: any;
    Executable: any;
    Globals(...values: any[]): any;
    HasCommand(...values: any[]): any;
    HasIcon(...values: any[]): any;
    Icons(...values: any[]): any;
    Id: any;
    Libraries(...values: any[]): any;
    LibraryPath(...values: any[]): any;
    Name: any;
    Quit(...values: any[]): any;
    Symbols(...values: any[]): any;
    Version: any;
};

declare class AudioPlayer {
    Buffering: any;
    Duration: any;
    Latency: any;
    Loop: any;
    Muted: any;
    OnEnded: any;
    OnError: any;
    Password: any;
    Pause(...values: any[]): any;
    Play(...values: any[]): any;
    Playing: any;
    Position: any;
    Seek(...values: any[]): any;
    Seekable: any;
    Stop(...values: any[]): any;
    Uri: any;
    User: any;
    Volume: any;
}

declare class Bytes {
    At(...values: any[]): any;
    Concat(...values: any[]): any;
    Equals(...values: any[]): any;
    Length: any;
    Slice(...values: any[]): any;
    ToBase64(...values: any[]): any;
    ToHex(...values: any[]): any;
    ToText(...values: any[]): any;
    toJSON(...values: any[]): any;
    toString(...values: any[]): any;
}

declare const Clipboard: {
    Copy(...values: any[]): any;
    CopyImage(...values: any[]): any;
    Paste(...values: any[]): any;
    PasteImage(...values: any[]): any;
};

declare class Connection {
    Close(...values: any[]): any;
    Columns(...values: any[]): any;
    Dialect: any;
    Execute(...values: any[]): any;
    Open: any;
    Path: any;
    Query(...values: any[]): any;
    Script(...values: any[]): any;
    Tables: any;
    Transaction(...values: any[]): any;
}

declare class Day {
    Add(...values: any[]): any;
    Between(...values: any[]): any;
    Today: any;
    Weekday(...values: any[]): any;
}

declare class Decimal {
    Abs(...values: any[]): any;
    IsExact: any;
    Number(...values: any[]): any;
    Round(...values: any[]): any;
    Scale: any;
    Sign: any;
    Trim(...values: any[]): any;
    toJSON(...values: any[]): any;
    toString(...values: any[]): any;
}

declare const Desktop: {
    CacheDirectory: any;
    ConfigDirectory: any;
    DataDirectory: any;
    Entries: any;
};

declare const Dialog: {
    Color(...values: any[]): any;
    OpenFile(...values: any[]): any;
    SaveFile(...values: any[]): any;
    SelectFolder(...values: any[]): any;
};

declare const Dictionary: {
    Count(...values: any[]): any;
    Entries(...values: any[]): any;
    Has(...values: any[]): any;
    Keys(...values: any[]): any;
    Values(...values: any[]): any;
};

declare const Directory: {
    Copy(...values: any[]): any;
    Delete(...values: any[]): any;
    DeleteTree(...values: any[]): any;
    Files(...values: any[]): any;
    Folders(...values: any[]): any;
    List(...values: any[]): any;
    Make(...values: any[]): any;
};

declare const Environment: {
    CurrentDirectory: any;
    Get(...values: any[]): any;
    HasDisplay: any;
    HomeDirectory: any;
    HostName: any;
    OS: any;
    OSVersion: any;
    ProcessId: any;
    ProcessorCount: any;
    Set(...values: any[]): any;
    TempDirectory: any;
    UserName: any;
    Variables: any;
};

declare const File: {
    Absolute(...values: any[]): any;
    Append(...values: any[]): any;
    BaseName(...values: any[]): any;
    Copy(...values: any[]): any;
    Delete(...values: any[]): any;
    Directory(...values: any[]): any;
    Exists(...values: any[]): any;
    Extension(...values: any[]): any;
    Hash(...values: any[]): any;
    Info(...values: any[]): any;
    IsDir(...values: any[]): any;
    IsExtension(...values: any[]): any;
    Join(...values: any[]): any;
    Load(...values: any[]): any;
    LoadBytes(...values: any[]): any;
    LoadJson(...values: any[]): any;
    LoadXml(...values: any[]): any;
    Name(...values: any[]): any;
    Open(...values: any[]): any;
    Relative(...values: any[]): any;
    Rename(...values: any[]): any;
    Save(...values: any[]): any;
    SaveBytes(...values: any[]): any;
    SaveJson(...values: any[]): any;
    SaveXml(...values: any[]): any;
    Trash(...values: any[]): any;
    Watch(...values: any[]): any;
    Within(...values: any[]): any;
};

declare const Hash: {
    Md5(...values: any[]): any;
    Sha1(...values: any[]): any;
    Sha256(...values: any[]): any;
    Sha512(...values: any[]): any;
};

declare const Http: {
    Client(...values: any[]): any;
    Delete(...values: any[]): any;
    DeleteWait(...values: any[]): any;
    Get(...values: any[]): any;
    GetWait(...values: any[]): any;
    Head(...values: any[]): any;
    HeadWait(...values: any[]): any;
    Patch(...values: any[]): any;
    PatchWait(...values: any[]): any;
    Post(...values: any[]): any;
    PostWait(...values: any[]): any;
    Put(...values: any[]): any;
    PutWait(...values: any[]): any;
    Request(...values: any[]): any;
    RequestWait(...values: any[]): any;
    Server(...values: any[]): any;
    Stream(...values: any[]): any;
};

declare class HttpClient {
    Auth: any;
    BaseUrl: any;
    Cookies: any;
    Delete(...values: any[]): any;
    DeleteWait(...values: any[]): any;
    FollowRedirects: any;
    Get(...values: any[]): any;
    GetWait(...values: any[]): any;
    Head(...values: any[]): any;
    HeadWait(...values: any[]): any;
    Headers: any;
    IdleTimeout: any;
    Language: any;
    Log: any;
    MaxConns: any;
    MaxPerHost: any;
    Patch(...values: any[]): any;
    PatchWait(...values: any[]): any;
    Post(...values: any[]): any;
    PostWait(...values: any[]): any;
    Proxy: any;
    Put(...values: any[]): any;
    PutWait(...values: any[]): any;
    Request(...values: any[]): any;
    RequestWait(...values: any[]): any;
    Stream(...values: any[]): any;
    Timeout: any;
    UserAgent: any;
}

declare class HttpRequest {
    Answer(...values: any[]): any;
    Multipart(...values: any[]): any;
}

declare class HttpServer {
    Allow: any;
    Auth: any;
    Host: any;
    Port: any;
    Request: any;
    Running: any;
    ServerName: any;
    Start(...values: any[]): any;
    Stop(...values: any[]): any;
    Tls: any;
    Url: any;
}

declare const Locale: {
    Available: any;
    Compare(...values: any[]): any;
    Context(...values: any[]): any;
    Currency(...values: any[]): any;
    Current: any;
    Date(...values: any[]): any;
    DecimalPoint: any;
    Matches(...values: any[]): any;
    Number(...values: any[]): any;
    Parse(...values: any[]): any;
    Plural(...values: any[]): any;
    Read(...values: any[]): any;
    Text(...values: any[]): any;
    Write(...values: any[]): any;
};

declare const Lock: {
    Hold(...values: any[]): any;
};

declare const Logger: {
    Debug(...values: any[]): any;
    Error(...values: any[]): any;
    Info(...values: any[]): any;
    Level: any;
    Target: any;
    Warning(...values: any[]): any;
};

declare class MenuItem {
    Click(...values: any[]): any;
    Enabled: any;
    EventNames(...values: any[]): any;
    Items: any;
    Name: any;
    PropertyNames(...values: any[]): any;
    Value: any;
}

declare const Message: {
    Error(...values: any[]): any;
    Info(...values: any[]): any;
    Warning(...values: any[]): any;
};

declare class Multipart {
    Field(...values: any[]): any;
    File(...values: any[]): any;
    Length: any;
    Part(...values: any[]): any;
}

declare class Painter {
    Antialias: any;
    Arc(...values: any[]): any;
    ArcNegative(...values: any[]): any;
    Clip(...values: any[]): any;
    ClipRectangle(...values: any[]): any;
    ClosePath(...values: any[]): any;
    Color: any;
    CurveTo(...values: any[]): any;
    Dark: any;
    Fill(...values: any[]): any;
    Font: any;
    Foreground: any;
    Image(...values: any[]): any;
    LineCap: any;
    LineDash: any;
    LineJoin: any;
    LineTo(...values: any[]): any;
    LineWidth: any;
    MoveTo(...values: any[]): any;
    Polygon(...values: any[]): any;
    Polyline(...values: any[]): any;
    Pop(...values: any[]): any;
    Push(...values: any[]): any;
    Rectangle(...values: any[]): any;
    Rotate(...values: any[]): any;
    Scale(...values: any[]): any;
    Stroke(...values: any[]): any;
    Text(...values: any[]): any;
    TextHeight(...values: any[]): any;
    TextWidth(...values: any[]): any;
    Translate(...values: any[]): any;
}

declare const Printer: {
    Default: any;
    Names: any;
    Papers: any;
    Send(...values: any[]): any;
    ToFile(...values: any[]): any;
};

declare const Screen: {
    Height: any;
    Monitors(...values: any[]): any;
    Scale: any;
    Width: any;
};

declare const Settings: {
    Clear(...values: any[]): any;
    Delete(...values: any[]): any;
    Get(...values: any[]): any;
    Has(...values: any[]): any;
    Keys(...values: any[]): any;
    Path: any;
    Set(...values: any[]): any;
};

declare class Task {
    Report(...values: any[]): any;
    Start(...values: any[]): any;
    Stop(...values: any[]): any;
    Stopping: any;
}

declare const Text: {
    Bounds(...values: any[]): any;
    Escape(...values: any[]): any;
    Font: any;
    Height(...values: any[]): any;
    IndexAt(...values: any[]): any;
    LineOf(...values: any[]): any;
    Lines(...values: any[]): any;
    OffsetAt(...values: any[]): any;
    Size(...values: any[]): any;
    Width(...values: any[]): any;
};

declare const Time: {
    Add(...values: any[]): any;
    Between(...values: any[]): any;
    Now: any;
    Seconds(...values: any[]): any;
};

declare const Xml: {
    Available: any;
    Element(...values: any[]): any;
    Parse(...values: any[]): any;
    ParseBytes(...values: any[]): any;
    Stringify(...values: any[]): any;
};

declare class XmlDocument {
    Root: any;
}

declare class XmlNode {
    Add(...values: any[]): any;
    Attr(...values: any[]): any;
    AttrNS(...values: any[]): any;
    AttributeNames(...values: any[]): any;
    Children: any;
    Copy(...values: any[]): any;
    Find(...values: any[]): any;
    FindAll(...values: any[]): any;
    Insert(...values: any[]): any;
    Name: any;
    Namespace: any;
    Parent: any;
    Prefix: any;
    Remove(...values: any[]): any;
    RemoveAttr(...values: any[]): any;
    RemoveAttrNS(...values: any[]): any;
    SetAttr(...values: any[]): any;
    SetAttrNS(...values: any[]): any;
    SetNamespace(...values: any[]): any;
    Text: any;
}

/*
 * **Empty, and it used not to be.** The Timer class was declared here by hand,
 * because it lives in rad.js and nothing answered it: PropertyNames refuses a
 * class that is not a widget, and there was no other road. It went stale the way
 * a hand-written list does -- Timer.After was missing, so an editor reported that
 * it did not exist, on the verb the whole language story leans on for having
 * replaced setTimeout.
 *
 * The generator walks the libraries now, and Widget.Members answers for a class of
 * rad.js the same as for anything else, so this has nothing left to hold. It
 * stays as the place for a class that *still* cannot be reached -- two words is
 * cheaper than the next stale row.
 */

/* ------------------------------------------------------------------ *
/* The libraries that ship with the runtime, by the same introspection. */
/* A project reaches one through `uses` in its project.json.             */
/* Parameters are not declared: no way to reach a library class's own   */
/* signatures exists yet, and a name is worth more than a guess.        */
/* ------------------------------------------------------------------ */

/** runtime/js/Timer. Every member: docs/reference/globals/Timer.md */
declare class Timer {
    /**  */
    Enabled: any | null;
    Start(...values: any[]): void;
    Stop(...values: any[]): void;
    Once(...values: any[]): void;
    static After(...values: any[]): any;
    static Every(...values: any[]): any;
}

/** runtime/js/Stopwatch. Every member: docs/reference/globals/Stopwatch.md */
declare class Stopwatch {
    /**  */
    Running: any | null;
    /**  */
    Elapsed: any | null;
    Start(...values: any[]): void;
    Stop(...values: any[]): void;
    Reset(...values: any[]): void;
}

/** runtime/js/Match. Every member: docs/reference/globals/Match.md */
declare class Match {
    Group(...values: any[]): void;
}

/** runtime/js/Regex. Every member: docs/reference/globals/Regex.md */
declare class Regex {
    /**  */
    Pattern: any | null;
    IsMatch(...values: any[]): void;
    Match(...values: any[]): void;
    Matches(...values: any[]): void;
    Replace(...values: any[]): void;
    Split(...values: any[]): void;
    static Escape(...values: any[]): any;
}

/** runtime/js/Record. Every member: docs/reference/globals/Record.md */
declare const Record: {
    new (...values: any[]): any;
    Load(...values: any[]): any;
    LoadXml(...values: any[]): any;
    Apply(...values: any[]): any;
    Serialize(...values: any[]): any;
    Clone(...values: any[]): any;
    Validate(...values: any[]): any;
    PropertyNames(...values: any[]): any;
    PropertyOptions(...values: any[]): any;
    PropertyInfo(...values: any[]): any;
    Dump(...values: any[]): any;
    ToXml(...values: any[]): any;
    SaveXml(...values: any[]): any;
};

/** runtime/js/Table. Every member: docs/reference/globals/Table.md */
declare class Table {
    /**  */
    Name: any | null;
    /**  */
    Connection: any | null;
    /**  */
    Shape: any | null;
    Where(...values: any[]): void;
    All(...values: any[]): void;
    Find(...values: any[]): void;
    Count(...values: any[]): void;
    Insert(...values: any[]): void;
    Update(...values: any[]): void;
    Save(...values: any[]): void;
    Delete(...values: any[]): void;
}

/** charts/Chart. Every member: docs/reference/libraries/Chart.md */
declare class Chart extends Component {
    /** One of "Bar" | "Line" | "Area" | "Pie" | "Doughnut". `Bar` by default. */
    Type: string | null;
    /**  `` by default. */
    Series: any[] | null;
    /**  `` by default. */
    Labels: any[] | null;
    /**  `` by default. */
    Marks: any[] | null;
    /** One of "None" | "Top" | "Bottom". `Bottom` by default. */
    Legend: string | null;
    /**  `true` by default. */
    Grid: boolean | null;
    /**  `false` by default. */
    Stacked: boolean | null;
    /**  `false` by default. */
    ShowValues: boolean | null;
    /**  */
    Title: string | null;
    /**  */
    YMin: string | null;
    /**  */
    YMax: string | null;
    /**  `0` by default. */
    Decimals: number | null;
    /**  `true` by default. */
    Antialias: boolean | null;
    /**  `false` by default. */
    Curved: boolean | null;
    /**  `true` by default. */
    Reduced: boolean | null;
    /**  `0` by default. */
    From: number | null;
    /**  `0` by default. */
    Count: number | null;
    /**  `false` by default. */
    Zoomable: boolean | null;
    /** One of "Fixed" | "Horizontal" | "Vertical". `Vertical` by default. */
    Arrangement: string | null;
    /**  `Order` by default. */
    Placement: string | null;
    /**  `0` by default. */
    Spacing: number | null;
    /**  `false` by default. */
    Homogeneous: boolean | null;
    /**  `true` by default. */
    Anchored: boolean | null;
    /**  `[object Object]` by default. */
    Children: any[] | null;
    /**  `Form` by default. */
    Name: string | null;
    /**  `0` by default. */
    X: number | null;
    /**  `0` by default. */
    Y: number | null;
    /**  `320` by default. */
    Width: number | null;
    /**  `220` by default. */
    Height: number | null;
    /**  `0` by default. */
    MinWidth: number | null;
    /**  `0` by default. */
    MinHeight: number | null;
    /**  `true` by default. */
    Visible: boolean | null;
    /**  `true` by default. */
    Enabled: boolean | null;
    /**  */
    Action: string | null;
    /**  `false` by default. */
    Focusable: boolean | null;
    /**  `false` by default. */
    Focused: boolean | null;
    /**  `false` by default. */
    Expand: boolean | null;
    /**  `false` by default. */
    HExpand: boolean | null;
    /**  `false` by default. */
    VExpand: boolean | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    HAlign: string | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    VAlign: string | null;
    /**  `1` by default. */
    ColumnSpan: number | null;
    /**  `0` by default. */
    TabIndex: number | null;
    /**  `0` by default. */
    Margin: number | null;
    /**  */
    Style: string | null;
    /**  */
    Background: string | null;
    /**  */
    Foreground: string | null;
    /**  */
    Font: string | null;
    /**  */
    Radius: string | null;
    /**  */
    Padding: string | null;
    /**  */
    Shortcut: string | null;
    /**  */
    Shadow: string | null;
    /**  */
    Border: string | null;
    /**  `1` by default. */
    FontScale: number | null;
    /**  `1` by default. */
    Opacity: number | null;
    /**  `false` by default. */
    Dark: boolean | null;
    /**  */
    Tooltip: string | null;
    /** One of "Auto" | "Arrow" | "Hand" | "Grab" | "Grabbing" | "Text" | "VerticalText" | "Wait" | "Progress" | "Help" | "Crosshair" | "Cell" | "ContextMenu" | "Move" | "Scroll" | "Copy" | "Link" | "NoDrop" | "NotAllowed" | "ZoomIn" | "ZoomOut" | "None" | "ResizeHorizontal" | "ResizeVertical" | "ResizeTopLeft" | "ResizeTopRight" | "ResizeColumn" | "ResizeRow". `Auto` by default. */
    Cursor: string | null;
    /**  */
    DragData: string | null;
    /**  `false` by default. */
    AcceptDrop: boolean | null;
    /**  `false` by default. */
    AcceptFiles: boolean | null;
    /**  */
    Menu: any | null;
    /**  */
    Item: any | null;
    Refresh(...values: any[]): void;
    Save(...values: any[]): void;
    Canvas_Draw(...values: any[]): void;
    Canvas_MouseWheel(...values: any[]): void;
    Canvas_MouseMove(...values: any[]): void;
    Canvas_MouseLeave(...values: any[]): void;
    Canvas_MouseDown(...values: any[]): void;
    Canvas_MouseUp(...values: any[]): void;
    Canvas_DblClick(...values: any[]): void;
    FocusNext(...values: any[]): void;
    FocusPrevious(...values: any[]): void;
    Reorder(...values: any[]): void;
    PickAt(...values: any[]): void;
    ContainerAt(...values: any[]): void;
    LocalPoint(...values: any[]): void;
    Add(...values: any[]): void;
    Clear(...values: any[]): void;
    AddNode(...values: any[]): void;
    BuildChildren(...values: any[]): void;
    PopupMenu(...values: any[]): void;
    Show(...values: any[]): void;
    Hide(...values: any[]): void;
    Move(...values: any[]): void;
    Resize(...values: any[]): void;
    SizeRequest(...values: any[]): void;
    SetFocus(...values: any[]): void;
    Delete(...values: any[]): void;
    Emit(...values: any[]): void;
    On(...values: any[]): void;
    OriginIn(...values: any[]): void;
    Bounds(...values: any[]): void;
    PropertyOptions(...values: any[]): void;
    TextProperties(...values: any[]): void;
    EventNames(...values: any[]): void;
    StyleRule(...values: any[]): void;
    CssNode(...values: any[]): void;
    Remove(...values: any[]): void;
    Raise(...values: any[]): void;
    Lower(...values: any[]): void;
    PropertyNames(...values: any[]): void;
    Serialize(...values: any[]): void;
    Dump(...values: any[]): void;
    Apply(...values: any[]): void;
    Declared(...values: any[]): void;
    Fill(...values: any[]): void;
    SetItem(...values: any[]): void;
    SetDesign(...values: any[]): void;
    DesignValue(...values: any[]): void;
}

/** dialog/AskText. Every member: docs/reference/libraries/AskText.md */
declare class AskText extends Form {
    /**  */
    Text: string | null;
    /**  */
    Icon: string | null;
    /**  `false` by default. */
    Modal: boolean | null;
    /**  */
    DefaultButton: any | null;
    /**  `[object Object]` by default. */
    CancelButton: any | null;
    /**  `false` by default. */
    Resizable: boolean | null;
    /**  `false` by default. */
    Maximized: boolean | null;
    /**  `false` by default. */
    FullScreen: boolean | null;
    /**  `false` by default. */
    HideOnClose: boolean | null;
    /**  */
    Caption: string | null;
    /**  `[object Object],[object Object],[object Object],[object Object],[object Object]` by default. */
    Controls: any[] | null;
    /**  `` by default. */
    Menus: any[] | null;
    /**  `` by default. */
    Actions: any[] | null;
    /** One of "Fixed" | "Horizontal" | "Vertical". `Fixed` by default. */
    Arrangement: string | null;
    /**  `Coordinates` by default. */
    Placement: string | null;
    /**  `0` by default. */
    Spacing: number | null;
    /**  `false` by default. */
    Homogeneous: boolean | null;
    /**  `true` by default. */
    Anchored: boolean | null;
    /**  `[object Object],[object Object],[object Object],[object Object],[object Object]` by default. */
    Children: any[] | null;
    /**  `Form` by default. */
    Name: string | null;
    /**  `0` by default. */
    X: number | null;
    /**  `0` by default. */
    Y: number | null;
    /**  `380` by default. */
    Width: number | null;
    /**  `140` by default. */
    Height: number | null;
    /**  `0` by default. */
    MinWidth: number | null;
    /**  `0` by default. */
    MinHeight: number | null;
    /**  `false` by default. */
    Visible: boolean | null;
    /**  `true` by default. */
    Enabled: boolean | null;
    /**  */
    Action: string | null;
    /**  `false` by default. */
    Focusable: boolean | null;
    /**  `false` by default. */
    Focused: boolean | null;
    /**  `false` by default. */
    Expand: boolean | null;
    /**  `false` by default. */
    HExpand: boolean | null;
    /**  `false` by default. */
    VExpand: boolean | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    HAlign: string | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    VAlign: string | null;
    /**  `1` by default. */
    ColumnSpan: number | null;
    /**  `0` by default. */
    TabIndex: number | null;
    /**  `0` by default. */
    Margin: number | null;
    /**  */
    Style: string | null;
    /**  */
    Background: string | null;
    /**  */
    Foreground: string | null;
    /**  */
    Font: string | null;
    /**  */
    Radius: string | null;
    /**  */
    Padding: string | null;
    /**  */
    Shortcut: string | null;
    /**  */
    Shadow: string | null;
    /**  */
    Border: string | null;
    /**  `1` by default. */
    FontScale: number | null;
    /**  `1` by default. */
    Opacity: number | null;
    /**  `false` by default. */
    Dark: boolean | null;
    /**  */
    Tooltip: string | null;
    /** One of "Auto" | "Arrow" | "Hand" | "Grab" | "Grabbing" | "Text" | "VerticalText" | "Wait" | "Progress" | "Help" | "Crosshair" | "Cell" | "ContextMenu" | "Move" | "Scroll" | "Copy" | "Link" | "NoDrop" | "NotAllowed" | "ZoomIn" | "ZoomOut" | "None" | "ResizeHorizontal" | "ResizeVertical" | "ResizeTopLeft" | "ResizeTopRight" | "ResizeColumn" | "ResizeRow". `Auto` by default. */
    Cursor: string | null;
    /**  */
    DragData: string | null;
    /**  `false` by default. */
    AcceptDrop: boolean | null;
    /**  `false` by default. */
    AcceptFiles: boolean | null;
    /**  */
    Menu: any | null;
    /**  */
    Item: any | null;
    BtnOk_Click(...values: any[]): void;
    BtnCancel_Click(...values: any[]): void;
    Show(...values: any[]): void;
    Close(...values: any[]): void;
    Center(...values: any[]): void;
    Minimize(...values: any[]): void;
    Serialize(...values: any[]): void;
    SaveForm(...values: any[]): void;
    FocusNext(...values: any[]): void;
    FocusPrevious(...values: any[]): void;
    Reorder(...values: any[]): void;
    PickAt(...values: any[]): void;
    ContainerAt(...values: any[]): void;
    LocalPoint(...values: any[]): void;
    Add(...values: any[]): void;
    Clear(...values: any[]): void;
    AddNode(...values: any[]): void;
    BuildChildren(...values: any[]): void;
    PopupMenu(...values: any[]): void;
    Hide(...values: any[]): void;
    Move(...values: any[]): void;
    Resize(...values: any[]): void;
    SizeRequest(...values: any[]): void;
    SetFocus(...values: any[]): void;
    Delete(...values: any[]): void;
    Emit(...values: any[]): void;
    On(...values: any[]): void;
    OriginIn(...values: any[]): void;
    Bounds(...values: any[]): void;
    PropertyOptions(...values: any[]): void;
    TextProperties(...values: any[]): void;
    EventNames(...values: any[]): void;
    StyleRule(...values: any[]): void;
    CssNode(...values: any[]): void;
    Remove(...values: any[]): void;
    Raise(...values: any[]): void;
    Lower(...values: any[]): void;
    PropertyNames(...values: any[]): void;
    Dump(...values: any[]): void;
    Apply(...values: any[]): void;
    Declared(...values: any[]): void;
    Fill(...values: any[]): void;
    SetItem(...values: any[]): void;
    SetDesign(...values: any[]): void;
    DesignValue(...values: any[]): void;
    static Prompt(...values: any[]): any;
}

/** dialog/Confirm. Every member: docs/reference/libraries/Confirm.md */
declare class Confirm extends Form {
    /**  */
    Text: string | null;
    /**  */
    Icon: string | null;
    /**  `false` by default. */
    Modal: boolean | null;
    /**  */
    DefaultButton: any | null;
    /**  `[object Object]` by default. */
    CancelButton: any | null;
    /**  `false` by default. */
    Resizable: boolean | null;
    /**  `false` by default. */
    Maximized: boolean | null;
    /**  `false` by default. */
    FullScreen: boolean | null;
    /**  `false` by default. */
    HideOnClose: boolean | null;
    /**  */
    Caption: string | null;
    /**  `[object Object],[object Object],[object Object]` by default. */
    Controls: any[] | null;
    /**  `` by default. */
    Menus: any[] | null;
    /**  `` by default. */
    Actions: any[] | null;
    /** One of "Fixed" | "Horizontal" | "Vertical". `Fixed` by default. */
    Arrangement: string | null;
    /**  `Coordinates` by default. */
    Placement: string | null;
    /**  `0` by default. */
    Spacing: number | null;
    /**  `false` by default. */
    Homogeneous: boolean | null;
    /**  `true` by default. */
    Anchored: boolean | null;
    /**  `[object Object],[object Object],[object Object]` by default. */
    Children: any[] | null;
    /**  `Form` by default. */
    Name: string | null;
    /**  `0` by default. */
    X: number | null;
    /**  `0` by default. */
    Y: number | null;
    /**  `400` by default. */
    Width: number | null;
    /**  `150` by default. */
    Height: number | null;
    /**  `0` by default. */
    MinWidth: number | null;
    /**  `0` by default. */
    MinHeight: number | null;
    /**  `false` by default. */
    Visible: boolean | null;
    /**  `true` by default. */
    Enabled: boolean | null;
    /**  */
    Action: string | null;
    /**  `false` by default. */
    Focusable: boolean | null;
    /**  `false` by default. */
    Focused: boolean | null;
    /**  `false` by default. */
    Expand: boolean | null;
    /**  `false` by default. */
    HExpand: boolean | null;
    /**  `false` by default. */
    VExpand: boolean | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    HAlign: string | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    VAlign: string | null;
    /**  `1` by default. */
    ColumnSpan: number | null;
    /**  `0` by default. */
    TabIndex: number | null;
    /**  `0` by default. */
    Margin: number | null;
    /**  */
    Style: string | null;
    /**  */
    Background: string | null;
    /**  */
    Foreground: string | null;
    /**  */
    Font: string | null;
    /**  */
    Radius: string | null;
    /**  */
    Padding: string | null;
    /**  */
    Shortcut: string | null;
    /**  */
    Shadow: string | null;
    /**  */
    Border: string | null;
    /**  `1` by default. */
    FontScale: number | null;
    /**  `1` by default. */
    Opacity: number | null;
    /**  `false` by default. */
    Dark: boolean | null;
    /**  */
    Tooltip: string | null;
    /** One of "Auto" | "Arrow" | "Hand" | "Grab" | "Grabbing" | "Text" | "VerticalText" | "Wait" | "Progress" | "Help" | "Crosshair" | "Cell" | "ContextMenu" | "Move" | "Scroll" | "Copy" | "Link" | "NoDrop" | "NotAllowed" | "ZoomIn" | "ZoomOut" | "None" | "ResizeHorizontal" | "ResizeVertical" | "ResizeTopLeft" | "ResizeTopRight" | "ResizeColumn" | "ResizeRow". `Auto` by default. */
    Cursor: string | null;
    /**  */
    DragData: string | null;
    /**  `false` by default. */
    AcceptDrop: boolean | null;
    /**  `false` by default. */
    AcceptFiles: boolean | null;
    /**  */
    Menu: any | null;
    /**  */
    Item: any | null;
    BtnAccept_Click(...values: any[]): void;
    BtnCancel_Click(...values: any[]): void;
    Show(...values: any[]): void;
    Close(...values: any[]): void;
    Center(...values: any[]): void;
    Minimize(...values: any[]): void;
    Serialize(...values: any[]): void;
    SaveForm(...values: any[]): void;
    FocusNext(...values: any[]): void;
    FocusPrevious(...values: any[]): void;
    Reorder(...values: any[]): void;
    PickAt(...values: any[]): void;
    ContainerAt(...values: any[]): void;
    LocalPoint(...values: any[]): void;
    Add(...values: any[]): void;
    Clear(...values: any[]): void;
    AddNode(...values: any[]): void;
    BuildChildren(...values: any[]): void;
    PopupMenu(...values: any[]): void;
    Hide(...values: any[]): void;
    Move(...values: any[]): void;
    Resize(...values: any[]): void;
    SizeRequest(...values: any[]): void;
    SetFocus(...values: any[]): void;
    Delete(...values: any[]): void;
    Emit(...values: any[]): void;
    On(...values: any[]): void;
    OriginIn(...values: any[]): void;
    Bounds(...values: any[]): void;
    PropertyOptions(...values: any[]): void;
    TextProperties(...values: any[]): void;
    EventNames(...values: any[]): void;
    StyleRule(...values: any[]): void;
    CssNode(...values: any[]): void;
    Remove(...values: any[]): void;
    Raise(...values: any[]): void;
    Lower(...values: any[]): void;
    PropertyNames(...values: any[]): void;
    Dump(...values: any[]): void;
    Apply(...values: any[]): void;
    Declared(...values: any[]): void;
    Fill(...values: any[]): void;
    SetItem(...values: any[]): void;
    SetDesign(...values: any[]): void;
    DesignValue(...values: any[]): void;
    static Ask(...values: any[]): any;
}

/** markdown/Markdown. Every member: docs/reference/libraries/Markdown.md */
declare class Markdown extends Component {
    /**  */
    Text: string | null;
    /**  */
    Path: string | null;
    /**  */
    BaseFont: string | null;
    /**  */
    CodeFont: string | null;
    /**  `0` by default. */
    MaxWidth: number | null;
    /**  `24` by default. */
    Margins: number | null;
    /** One of "A4" | "Letter" | "A5". `A4` by default. */
    Paper: string | null;
    /**  `0` by default. */
    Scroll: number | null;
    /**  `0` by default. */
    ScrollMax: number | null;
    /**  `48` by default. */
    ContentHeight: number | null;
    /**  `` by default. */
    Headings: any[] | null;
    /**  */
    Selection: string | null;
    /** One of "Fixed" | "Horizontal" | "Vertical". `Vertical` by default. */
    Arrangement: string | null;
    /**  `Order` by default. */
    Placement: string | null;
    /**  `0` by default. */
    Spacing: number | null;
    /**  `false` by default. */
    Homogeneous: boolean | null;
    /**  `true` by default. */
    Anchored: boolean | null;
    /**  `[object Object]` by default. */
    Children: any[] | null;
    /**  `Form` by default. */
    Name: string | null;
    /**  `0` by default. */
    X: number | null;
    /**  `0` by default. */
    Y: number | null;
    /**  `480` by default. */
    Width: number | null;
    /**  `640` by default. */
    Height: number | null;
    /**  `0` by default. */
    MinWidth: number | null;
    /**  `0` by default. */
    MinHeight: number | null;
    /**  `true` by default. */
    Visible: boolean | null;
    /**  `true` by default. */
    Enabled: boolean | null;
    /**  */
    Action: string | null;
    /**  `false` by default. */
    Focusable: boolean | null;
    /**  `false` by default. */
    Focused: boolean | null;
    /**  `false` by default. */
    Expand: boolean | null;
    /**  `false` by default. */
    HExpand: boolean | null;
    /**  `false` by default. */
    VExpand: boolean | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    HAlign: string | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    VAlign: string | null;
    /**  `1` by default. */
    ColumnSpan: number | null;
    /**  `0` by default. */
    TabIndex: number | null;
    /**  `0` by default. */
    Margin: number | null;
    /**  */
    Style: string | null;
    /**  */
    Background: string | null;
    /**  */
    Foreground: string | null;
    /**  */
    Font: string | null;
    /**  */
    Radius: string | null;
    /**  */
    Padding: string | null;
    /**  */
    Shortcut: string | null;
    /**  */
    Shadow: string | null;
    /**  */
    Border: string | null;
    /**  `1` by default. */
    FontScale: number | null;
    /**  `1` by default. */
    Opacity: number | null;
    /**  `false` by default. */
    Dark: boolean | null;
    /**  */
    Tooltip: string | null;
    /** One of "Auto" | "Arrow" | "Hand" | "Grab" | "Grabbing" | "Text" | "VerticalText" | "Wait" | "Progress" | "Help" | "Crosshair" | "Cell" | "ContextMenu" | "Move" | "Scroll" | "Copy" | "Link" | "NoDrop" | "NotAllowed" | "ZoomIn" | "ZoomOut" | "None" | "ResizeHorizontal" | "ResizeVertical" | "ResizeTopLeft" | "ResizeTopRight" | "ResizeColumn" | "ResizeRow". `Auto` by default. */
    Cursor: string | null;
    /**  */
    DragData: string | null;
    /**  `false` by default. */
    AcceptDrop: boolean | null;
    /**  `false` by default. */
    AcceptFiles: boolean | null;
    /**  */
    Menu: any | null;
    /**  */
    Item: any | null;
    Load(...values: any[]): void;
    Refresh(...values: any[]): void;
    ScrollTo(...values: any[]): void;
    SelectAll(...values: any[]): void;
    Deselect(...values: any[]): void;
    Copy(...values: any[]): void;
    Find(...values: any[]): void;
    FindNext(...values: any[]): void;
    Save(...values: any[]): void;
    SavePdf(...values: any[]): void;
    Send(...values: any[]): void;
    Canvas_Paginate(...values: any[]): void;
    Canvas_DrawPage(...values: any[]): void;
    Canvas_Draw(...values: any[]): void;
    Canvas_MouseWheel(...values: any[]): void;
    Canvas_MouseDown(...values: any[]): void;
    Canvas_MouseMove(...values: any[]): void;
    Canvas_MouseUp(...values: any[]): void;
    Canvas_DblClick(...values: any[]): void;
    Canvas_KeyPress(...values: any[]): void;
    FocusNext(...values: any[]): void;
    FocusPrevious(...values: any[]): void;
    Reorder(...values: any[]): void;
    PickAt(...values: any[]): void;
    ContainerAt(...values: any[]): void;
    LocalPoint(...values: any[]): void;
    Add(...values: any[]): void;
    Clear(...values: any[]): void;
    AddNode(...values: any[]): void;
    BuildChildren(...values: any[]): void;
    PopupMenu(...values: any[]): void;
    Show(...values: any[]): void;
    Hide(...values: any[]): void;
    Move(...values: any[]): void;
    Resize(...values: any[]): void;
    SizeRequest(...values: any[]): void;
    SetFocus(...values: any[]): void;
    Delete(...values: any[]): void;
    Emit(...values: any[]): void;
    On(...values: any[]): void;
    OriginIn(...values: any[]): void;
    Bounds(...values: any[]): void;
    PropertyOptions(...values: any[]): void;
    TextProperties(...values: any[]): void;
    EventNames(...values: any[]): void;
    StyleRule(...values: any[]): void;
    CssNode(...values: any[]): void;
    Remove(...values: any[]): void;
    Raise(...values: any[]): void;
    Lower(...values: any[]): void;
    PropertyNames(...values: any[]): void;
    Serialize(...values: any[]): void;
    Dump(...values: any[]): void;
    Apply(...values: any[]): void;
    Declared(...values: any[]): void;
    Fill(...values: any[]): void;
    SetItem(...values: any[]): void;
    SetDesign(...values: any[]): void;
    DesignValue(...values: any[]): void;
}

/** package/Metainfo. Every member: docs/reference/libraries/Metainfo.md */
declare class Metainfo {
}

/** package/Nsis. Every member: docs/reference/libraries/Nsis.md */
declare class Nsis {
    static Script(...values: any[]): any;
    static Stage(...values: any[]): any;
    static Build(...values: any[]): any;
    static Ico(...values: any[]): any;
}

/** package/Package. Every member: docs/reference/libraries/Package.md */
declare class Package {
    static Write(...values: any[]): any;
}

/** qr/QrCode. Every member: docs/reference/libraries/QrCode.md */
declare class QrCode {
    /**  */
    Version: any | null;
    /**  */
    Ecc: any | null;
    /**  */
    Mask: any | null;
    /**  */
    Mode: any | null;
    /**  */
    Size: any | null;
    Dark(...values: any[]): void;
    Paint(...values: any[]): void;
    ToSvg(...values: any[]): void;
    ToText(...values: any[]): void;
    static Encode(...values: any[]): any;
}

/** qr/QrView. Every member: docs/reference/libraries/QrView.md */
declare class QrView extends Component {
    /**  */
    Text: string | null;
    /** One of "L" | "M" | "Q" | "H". `M` by default. */
    Ecc: string | null;
    /**  `4` by default. */
    QuietZone: number | null;
    /**  `#000000` by default. */
    Ink: string | null;
    /**  `#ffffff` by default. */
    Paper: string | null;
    /**  */
    Code: any | null;
    /**  */
    Problem: string | null;
    /** One of "Fixed" | "Horizontal" | "Vertical". `Vertical` by default. */
    Arrangement: string | null;
    /**  `Order` by default. */
    Placement: string | null;
    /**  `0` by default. */
    Spacing: number | null;
    /**  `false` by default. */
    Homogeneous: boolean | null;
    /**  `true` by default. */
    Anchored: boolean | null;
    /**  `[object Object]` by default. */
    Children: any[] | null;
    /**  `Form` by default. */
    Name: string | null;
    /**  `0` by default. */
    X: number | null;
    /**  `0` by default. */
    Y: number | null;
    /**  `160` by default. */
    Width: number | null;
    /**  `160` by default. */
    Height: number | null;
    /**  `0` by default. */
    MinWidth: number | null;
    /**  `0` by default. */
    MinHeight: number | null;
    /**  `true` by default. */
    Visible: boolean | null;
    /**  `true` by default. */
    Enabled: boolean | null;
    /**  */
    Action: string | null;
    /**  `false` by default. */
    Focusable: boolean | null;
    /**  `false` by default. */
    Focused: boolean | null;
    /**  `false` by default. */
    Expand: boolean | null;
    /**  `false` by default. */
    HExpand: boolean | null;
    /**  `false` by default. */
    VExpand: boolean | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    HAlign: string | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    VAlign: string | null;
    /**  `1` by default. */
    ColumnSpan: number | null;
    /**  `0` by default. */
    TabIndex: number | null;
    /**  `0` by default. */
    Margin: number | null;
    /**  */
    Style: string | null;
    /**  */
    Background: string | null;
    /**  */
    Foreground: string | null;
    /**  */
    Font: string | null;
    /**  */
    Radius: string | null;
    /**  */
    Padding: string | null;
    /**  */
    Shortcut: string | null;
    /**  */
    Shadow: string | null;
    /**  */
    Border: string | null;
    /**  `1` by default. */
    FontScale: number | null;
    /**  `1` by default. */
    Opacity: number | null;
    /**  `false` by default. */
    Dark: boolean | null;
    /**  */
    Tooltip: string | null;
    /** One of "Auto" | "Arrow" | "Hand" | "Grab" | "Grabbing" | "Text" | "VerticalText" | "Wait" | "Progress" | "Help" | "Crosshair" | "Cell" | "ContextMenu" | "Move" | "Scroll" | "Copy" | "Link" | "NoDrop" | "NotAllowed" | "ZoomIn" | "ZoomOut" | "None" | "ResizeHorizontal" | "ResizeVertical" | "ResizeTopLeft" | "ResizeTopRight" | "ResizeColumn" | "ResizeRow". `Auto` by default. */
    Cursor: string | null;
    /**  */
    DragData: string | null;
    /**  `false` by default. */
    AcceptDrop: boolean | null;
    /**  `false` by default. */
    AcceptFiles: boolean | null;
    /**  */
    Menu: any | null;
    /**  */
    Item: any | null;
    Refresh(...values: any[]): void;
    Save(...values: any[]): void;
    ToPng(...values: any[]): void;
    ToSvg(...values: any[]): void;
    Canvas_Draw(...values: any[]): void;
    FocusNext(...values: any[]): void;
    FocusPrevious(...values: any[]): void;
    Reorder(...values: any[]): void;
    PickAt(...values: any[]): void;
    ContainerAt(...values: any[]): void;
    LocalPoint(...values: any[]): void;
    Add(...values: any[]): void;
    Clear(...values: any[]): void;
    AddNode(...values: any[]): void;
    BuildChildren(...values: any[]): void;
    PopupMenu(...values: any[]): void;
    Show(...values: any[]): void;
    Hide(...values: any[]): void;
    Move(...values: any[]): void;
    Resize(...values: any[]): void;
    SizeRequest(...values: any[]): void;
    SetFocus(...values: any[]): void;
    Delete(...values: any[]): void;
    Emit(...values: any[]): void;
    On(...values: any[]): void;
    OriginIn(...values: any[]): void;
    Bounds(...values: any[]): void;
    PropertyOptions(...values: any[]): void;
    TextProperties(...values: any[]): void;
    EventNames(...values: any[]): void;
    StyleRule(...values: any[]): void;
    CssNode(...values: any[]): void;
    Remove(...values: any[]): void;
    Raise(...values: any[]): void;
    Lower(...values: any[]): void;
    PropertyNames(...values: any[]): void;
    Serialize(...values: any[]): void;
    Dump(...values: any[]): void;
    Apply(...values: any[]): void;
    Declared(...values: any[]): void;
    Fill(...values: any[]): void;
    SetItem(...values: any[]): void;
    SetDesign(...values: any[]): void;
    DesignValue(...values: any[]): void;
}

/** report/Report. Every member: docs/reference/libraries/Report.md */
declare class Report extends Component {
    /** One of "A4" | "Letter" | "A5". `A4` by default. */
    Paper: string | null;
    /** One of "Portrait" | "Landscape". `Portrait` by default. */
    Orientation: string | null;
    /**  `40` by default. */
    Margins: number | null;
    /**  `1` by default. */
    Page: number | null;
    /**  `` by default. */
    Data: any[] | null;
    /**  `[object Object]` by default. */
    Sections: any | null;
    /**  `1` by default. */
    PageCount: number | null;
    /** One of "Fixed" | "Horizontal" | "Vertical". `Vertical` by default. */
    Arrangement: string | null;
    /**  `Order` by default. */
    Placement: string | null;
    /**  `0` by default. */
    Spacing: number | null;
    /**  `false` by default. */
    Homogeneous: boolean | null;
    /**  `true` by default. */
    Anchored: boolean | null;
    /**  `[object Object]` by default. */
    Children: any[] | null;
    /**  `Form` by default. */
    Name: string | null;
    /**  `0` by default. */
    X: number | null;
    /**  `0` by default. */
    Y: number | null;
    /**  `480` by default. */
    Width: number | null;
    /**  `640` by default. */
    Height: number | null;
    /**  `0` by default. */
    MinWidth: number | null;
    /**  `0` by default. */
    MinHeight: number | null;
    /**  `true` by default. */
    Visible: boolean | null;
    /**  `true` by default. */
    Enabled: boolean | null;
    /**  */
    Action: string | null;
    /**  `false` by default. */
    Focusable: boolean | null;
    /**  `false` by default. */
    Focused: boolean | null;
    /**  `false` by default. */
    Expand: boolean | null;
    /**  `false` by default. */
    HExpand: boolean | null;
    /**  `false` by default. */
    VExpand: boolean | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    HAlign: string | null;
    /** One of "Auto" | "Start" | "End" | "Center" | "Fill". `Auto` by default. */
    VAlign: string | null;
    /**  `1` by default. */
    ColumnSpan: number | null;
    /**  `0` by default. */
    TabIndex: number | null;
    /**  `0` by default. */
    Margin: number | null;
    /**  */
    Style: string | null;
    /**  */
    Background: string | null;
    /**  */
    Foreground: string | null;
    /**  */
    Font: string | null;
    /**  */
    Radius: string | null;
    /**  */
    Padding: string | null;
    /**  */
    Shortcut: string | null;
    /**  */
    Shadow: string | null;
    /**  */
    Border: string | null;
    /**  `1` by default. */
    FontScale: number | null;
    /**  `1` by default. */
    Opacity: number | null;
    /**  `false` by default. */
    Dark: boolean | null;
    /**  */
    Tooltip: string | null;
    /** One of "Auto" | "Arrow" | "Hand" | "Grab" | "Grabbing" | "Text" | "VerticalText" | "Wait" | "Progress" | "Help" | "Crosshair" | "Cell" | "ContextMenu" | "Move" | "Scroll" | "Copy" | "Link" | "NoDrop" | "NotAllowed" | "ZoomIn" | "ZoomOut" | "None" | "ResizeHorizontal" | "ResizeVertical" | "ResizeTopLeft" | "ResizeTopRight" | "ResizeColumn" | "ResizeRow". `Auto` by default. */
    Cursor: string | null;
    /**  */
    DragData: string | null;
    /**  `false` by default. */
    AcceptDrop: boolean | null;
    /**  `false` by default. */
    AcceptFiles: boolean | null;
    /**  */
    Menu: any | null;
    /**  */
    Item: any | null;
    Refresh(...values: any[]): void;
    Save(...values: any[]): void;
    SavePdf(...values: any[]): void;
    Send(...values: any[]): void;
    Canvas_DrawPage(...values: any[]): void;
    Canvas_Draw(...values: any[]): void;
    FocusNext(...values: any[]): void;
    FocusPrevious(...values: any[]): void;
    Reorder(...values: any[]): void;
    PickAt(...values: any[]): void;
    ContainerAt(...values: any[]): void;
    LocalPoint(...values: any[]): void;
    Add(...values: any[]): void;
    Clear(...values: any[]): void;
    AddNode(...values: any[]): void;
    BuildChildren(...values: any[]): void;
    PopupMenu(...values: any[]): void;
    Show(...values: any[]): void;
    Hide(...values: any[]): void;
    Move(...values: any[]): void;
    Resize(...values: any[]): void;
    SizeRequest(...values: any[]): void;
    SetFocus(...values: any[]): void;
    Delete(...values: any[]): void;
    Emit(...values: any[]): void;
    On(...values: any[]): void;
    OriginIn(...values: any[]): void;
    Bounds(...values: any[]): void;
    PropertyOptions(...values: any[]): void;
    TextProperties(...values: any[]): void;
    EventNames(...values: any[]): void;
    StyleRule(...values: any[]): void;
    CssNode(...values: any[]): void;
    Remove(...values: any[]): void;
    Raise(...values: any[]): void;
    Lower(...values: any[]): void;
    PropertyNames(...values: any[]): void;
    Serialize(...values: any[]): void;
    Dump(...values: any[]): void;
    Apply(...values: any[]): void;
    Declared(...values: any[]): void;
    Fill(...values: any[]): void;
    SetItem(...values: any[]): void;
    SetDesign(...values: any[]): void;
    DesignValue(...values: any[]): void;
}
